// 托业核心词汇库 - 1216个高频单词（合并版）
// 包含托业考试所有高频词汇，分为122关，每关 10 个单词
// 自动生成于 2026/3/20 08:17:13
// 音标和例句来自 toeicWords-example.js，完整词库来自 toeicWords-full.js

export const toeicWords = [
  { word: 'occupation', phonetic: '/ˌɑːkjuˈpeɪʃn/', meaning: '职位', example: 'Please state your name, age, and occupation.', exampleTranslation: '请说明你的姓名、年龄和职业。' },
  { word: 'vacancy', phonetic: '/ˈveɪkənsi/', meaning: '空位', example: 'We have several job vacancies in our company.', exampleTranslation: '我们公司有几个职位空缺。' },
  { word: 'pay', phonetic: '', meaning: '待遇' },
  { word: 'leave', phonetic: '', meaning: '休假' },
  { word: 'promotion', phonetic: '/prəˈmoʊʃn/', meaning: '升迁', example: 'We are running a special promotion this week.', exampleTranslation: '我们本周正在进行特别促销。' },
  { word: 'demotion', phonetic: '', meaning: '降级' },
  { word: 'dismissal', phonetic: '', meaning: '解雇' },
  { word: 'president', phonetic: '', meaning: '董事长' },
  { word: 'supervisor', phonetic: '', meaning: '总管' },
  { word: 'bonus', phonetic: '', meaning: '分红' },
  { word: 'commute', phonetic: '', meaning: '通勤' },
  { word: 'opening', phonetic: '', meaning: '空缺' },
  { word: 'transit', phonetic: '', meaning: '中转' },
  { word: 'transportation', phonetic: '', meaning: '运输' },
  { word: 'billboard', phonetic: '', meaning: '告示牌' },
  { word: 'across-the-broad', phonetic: '', meaning: '全盘的' },
  { word: 'assembly', phonetic: '', meaning: '议会' },
  { word: 'attraction', phonetic: '', meaning: '吸引人之物' },
  { word: 'claim', phonetic: '', meaning: '主张' },
  { word: 'collapse', phonetic: '', meaning: '瓦解' },
  { word: 'condition', phonetic: '', meaning: '条件、状况' },
  { word: 'deficit-ridden', phonetic: '', meaning: '受举债之苦的' },
  { word: 'evidence', phonetic: '', meaning: '证据' },
  { word: 'explicitly', phonetic: '', meaning: '明确指出地' },
  { word: 'warrant', phonetic: '', meaning: '权限' },
  { word: 'harbinger', phonetic: '', meaning: '预兆' },
  { word: 'implicitly', phonetic: '', meaning: '暗含的' },
  { word: 'inconclusively', phonetic: '', meaning: '没有结论含糊不清地' },
  { word: 'conclusive', phonetic: '', meaning: '决定性的、确凿的' },
  { word: 'provisional', phonetic: '', meaning: '暂时的=tentatively' },
  { word: 'requirement', phonetic: '', meaning: '必要条件' },
  { word: 'reveal', phonetic: '', meaning: '损失，透露' },
  { word: 'scapegoat', phonetic: '', meaning: '替罪羊' },
  { word: 'account', phonetic: '/əˈkaʊnt/', meaning: '交易对象', example: 'I opened a savings account.', exampleTranslation: '我开了一个储蓄账户。' },
  { word: 'exhibition', phonetic: '', meaning: '展示会' },
  { word: 'presentation', phonetic: '', meaning: '发布会' },
  { word: 'dumping', phonetic: '', meaning: '倾销' },
  { word: 'embargo', phonetic: '', meaning: '禁止通商' },
  { word: 'grant', phonetic: '', meaning: '无偿帮助' },
  { word: 'margin', phonetic: '', meaning: '盈余' },
  { word: 'loss', phonetic: '', meaning: '损失' },
  { word: 'quotations', phonetic: '', meaning: '报价' },
  { word: 'references', phonetic: '', meaning: '照会对象，推荐人；介绍信；背景调查' },
  { word: 'self-restraint', phonetic: '', meaning: '自我设限' },
  { word: 'terms', phonetic: '', meaning: '支付条款' },
  { word: 'affiliation', phonetic: '', meaning: '附属' },
  { word: 'contract', phonetic: '', meaning: '合同' },
  { word: 'convention', phonetic: '', meaning: '大会' },
  { word: 'cooperation', phonetic: '', meaning: '合作' },
  { word: 'coordination', phonetic: '', meaning: '协调' },
  { word: 'employee', phonetic: '', meaning: '雇员' },
  { word: 'employer', phonetic: '', meaning: '雇工' },
  { word: 'labor', phonetic: '', meaning: '劳工' },
  { word: 'management', phonetic: '', meaning: '经营者' },
  { word: 'proposal', phonetic: '', meaning: '提议' },
  { word: 'protest', phonetic: '', meaning: '抗议' },
  { word: 'wage', phonetic: '', meaning: '发动、实施' },
  { word: 'get-together', phonetic: '', meaning: '亲朋好友的聚会' },
  { word: 'dedication', phonetic: '', meaning: '献辞' },
  { word: 'interpellation', phonetic: '', meaning: '质询' },
  { word: 'itinerary', phonetic: '', meaning: '路线，日程表' },
  { word: 'launch', phonetic: '', meaning: '开始' },
  { word: 'Diet', phonetic: '', meaning: '国会' },
  { word: 'sectionalism', phonetic: '', meaning: '派系主义' },
  { word: 'troubleshooter', phonetic: '', meaning: '调解纠纷的人' },
  { word: 'withdraw', phonetic: '/wɪðˈdrɔː/', meaning: '撤退，取钱', example: 'You can withdraw money from any ATM.', exampleTranslation: '你可以在任何 ATM 机取款。' },
  { word: 'baseball', phonetic: '', meaning: '棒球' },
  { word: 'football', phonetic: '', meaning: '美式足球' },
  { word: 'soccer', phonetic: '', meaning: '英式足球' },
  { word: 'tennis', phonetic: '', meaning: '网球' },
  { word: 'volleyball', phonetic: '', meaning: '排球' },
  { word: 'fishing', phonetic: '', meaning: '钓鱼' },
  { word: 'surfing', phonetic: '', meaning: '冲浪' },
  { word: 'sailing', phonetic: '', meaning: '帆船比赛' },
  { word: 'water-skiing', phonetic: '', meaning: '滑水' },
  { word: 'rowing', phonetic: '', meaning: '划船' },
  { word: 'sledding', phonetic: '', meaning: '滑雪橇' },
  { word: 'skating', phonetic: '', meaning: '溜冰' },
  { word: 'hiking', phonetic: '', meaning: '徒步旅行' },
  { word: 'contestant', phonetic: '', meaning: '选手' },
  { word: 'dope', phonetic: '', meaning: '服兴奋剂' },
  { word: 'elimination', phonetic: '', meaning: '淘汰' },
  { word: 'home-town', phonetic: '', meaning: '当地的' },
  { word: 'play-off', phonetic: '', meaning: '加赛' },
  { word: 'preliminary', phonetic: '', meaning: '预赛' },
  { word: 'record-breaking', phonetic: '', meaning: '破纪录的' },
  { word: 'runner-up', phonetic: '', meaning: '亚军' },
  { word: 'seed', phonetic: '', meaning: '种子选手' },
  { word: 'season-ticket', phonetic: '', meaning: '赛季联赛' },
  { word: 'semifinals', phonetic: '', meaning: '半决赛' },
  { word: 'visitor', phonetic: '', meaning: '客队' },
  { word: 'underdog', phonetic: '', meaning: '败方' },
  { word: 'goalkeeper', phonetic: '', meaning: '守门员' },
  { word: 'defense', phonetic: '', meaning: '后卫' },
  { word: 'jersey', phonetic: '', meaning: '运动衫' },
  { word: 'utilities', phonetic: '', meaning: '水电气费' },
  { word: 'acute', phonetic: '', meaning: '敏锐的' },
  { word: 'affluent', phonetic: '', meaning: '丰富的' },
  { word: 'hamper', phonetic: '', meaning: '阻碍，抑制' },
  { word: 'long-standing', phonetic: '', meaning: '经年累月的' },
  { word: 'long-term', phonetic: '', meaning: '长期的' },
  { word: 'mortgage', phonetic: '', meaning: '抵押' },
  { word: 'prestigious', phonetic: '', meaning: '有名声的' },
  { word: 'prospect', phonetic: '', meaning: '预估' },
  { word: 'recession', phonetic: '', meaning: '衰退，不景气' },
  { word: 'record', phonetic: '', meaning: '记录' },
  { word: 'soar', phonetic: '', meaning: '上升，突破' },
  { word: 'short-term', phonetic: '', meaning: '短期的' },
  { word: 'surpass', phonetic: '', meaning: '超越' },
  { word: 'vicinity', phonetic: '', meaning: '临近' },
  { word: 'demographics', phonetic: '', meaning: '人口统计' },
  { word: 'findings', phonetic: '', meaning: '调查结果' },
  { word: 'alternative', phonetic: '', meaning: '替代性' },
  { word: 'campaign', phonetic: '', meaning: '活动' },
  { word: 'covert', phonetic: '', meaning: '秘密的，（反）overt 公开的' },
  { word: 'prevalent', phonetic: '', meaning: '盛行的' },
  { word: 'probe', phonetic: '', meaning: '严密的调查' },
  { word: 'problematic', phonetic: '', meaning: '有问题的' },
  { word: 'projections', phonetic: '', meaning: '预测，推测' },
  { word: 'reception', phonetic: '', meaning: '接受' },
  { word: 'replacement', phonetic: '', meaning: '替代' },
  { word: 'screening', phonetic: '', meaning: '试镜' },
  { word: 'successive', phonetic: '', meaning: '相继的' },
  { word: 'unstable', phonetic: '', meaning: '不安定的' },
  { word: 'suspension', phonetic: '', meaning: '暂时中止' },
  { word: 'tabulation', phonetic: '', meaning: '表格' },
  { word: 'widespread', phonetic: '', meaning: '广泛普及的' },
  { word: 'witness', phonetic: '', meaning: '目击者' },
  { word: 'tumultuous', phonetic: '', meaning: '激昂的' },
  { word: 'turnout', phonetic: '', meaning: '集合的人群' },
  { word: 'line', phonetic: '', meaning: '铁路线' },
  { word: 'conductor', phonetic: '', meaning: '乘务员' },
  { word: 'junction', phonetic: '', meaning: '列车枢纽站' },
  { word: 'transfer', phonetic: '/trænsˈfɜːr/', meaning: '转乘', example: 'I want to transfer money to another account.', exampleTranslation: '我想转账到另一个账户。' },
  { word: 'lane', phonetic: '', meaning: '车道' },
  { word: 'turnpike', phonetic: '', meaning: '收费高速公路' },
  { word: 'shortcut', phonetic: '', meaning: '捷径' },
  { word: 'arrivals', phonetic: '', meaning: '到达' },
  { word: 'crew', phonetic: '', meaning: '机组成员' },
  { word: 'cumulonimbus', phonetic: '', meaning: '积雨云' },
  { word: 'departures', phonetic: '', meaning: '处罚航班' },
  { word: 'evacuate', phonetic: '', meaning: '撤退' },
  { word: 'intersection', phonetic: '', meaning: '交叉路口' },
  { word: 'non-refundable', phonetic: '', meaning: '不可退款的' },
  { word: 'non-stop', phonetic: '', meaning: '直达车' },
  { word: 'overbook', phonetic: '', meaning: '超过既定预约人数' },
  { word: 'derail', phonetic: '', meaning: '脱轨' },
  { word: 'reconfirmation', phonetic: '', meaning: '再确认' },
  { word: 'subway', phonetic: '', meaning: '地铁' },
  { word: 'accused', phonetic: '', meaning: '被告' },
  { word: 'adult', phonetic: '', meaning: '成年人' },
  { word: 'allegedly', phonetic: '', meaning: '据称' },
  { word: 'casualty', phonetic: '', meaning: '死伤者' },
  { word: 'crack', phonetic: '', meaning: '龟裂' },
  { word: 'crash', phonetic: '', meaning: '坠机' },
  { word: 'damages', phonetic: '', meaning: '损害赔偿金' },
  { word: 'defendant', phonetic: '', meaning: '被告' },
  { word: 'devastating', phonetic: '', meaning: '破坏性的' },
  { word: 'drawing', phonetic: '', meaning: '抽签' },
  { word: 'inheritance', phonetic: '', meaning: '继承' },
  { word: 'hit', phonetic: '', meaning: '袭击' },
  { word: 'fire', phonetic: '', meaning: '火灾' },
  { word: 'jolt', phonetic: '', meaning: '晃动' },
  { word: 'lawyer', phonetic: '', meaning: '律师' },
  { word: 'lottery', phonetic: '', meaning: '彩票' },
  { word: 'minor', phonetic: '', meaning: '未成年人' },
  { word: 'plaintiff', phonetic: '', meaning: '原告，起诉者' },
  { word: 'prosecution', phonetic: '', meaning: '起诉' },
  { word: 'property', phonetic: '', meaning: '财产' },
  { word: 'rock', phonetic: '', meaning: '（地震等）前后摇晃' },
  { word: 'shower', phonetic: '', meaning: '阵雨' },
  { word: 'storm', phonetic: '', meaning: '暴风雨' },
  { word: 'rainstorm', phonetic: '', meaning: '雨暴' },
  { word: 'rainfall', phonetic: '', meaning: '降雨量' },
  { word: 'hail', phonetic: '', meaning: '冰雹' },
  { word: 'fog', phonetic: '', meaning: '雾' },
  { word: 'sleet', phonetic: '', meaning: '雨夹雪' },
  { word: 'blizzard', phonetic: '', meaning: '大风雪' },
  { word: 'breeze', phonetic: '', meaning: '微风' },
  { word: 'tornado', phonetic: '', meaning: '龙卷风' },
  { word: 'temperature', phonetic: '', meaning: '气温' },
  { word: 'thermometer', phonetic: '', meaning: '温度计' },
  { word: 'humidity', phonetic: '', meaning: '湿度' },
  { word: 'flood', phonetic: '', meaning: '洪水' },
  { word: 'avalanche', phonetic: '', meaning: '雪崩' },
  { word: 'Antarctic', phonetic: '', meaning: '南极' },
  { word: 'Arctic', phonetic: '', meaning: '北极' },
  { word: 'chill', phonetic: '', meaning: '寒气的' },
  { word: 'crisp', phonetic: '', meaning: '舒爽的' },
  { word: 'exploration', phonetic: '', meaning: '探险队' },
  { word: 'scorching', phonetic: '', meaning: '酷热的' },
  { word: 'snowstorm', phonetic: '', meaning: '暴风雪' },
  { word: 'sizzling', phonetic: '', meaning: '（水滚热时的）嘶嘶声' },
  { word: 'summery', phonetic: '', meaning: '夏季的' },
  { word: 'visibility', phonetic: '', meaning: '可见度' },
  { word: 'weatherperson', phonetic: '', meaning: '天气预报员' },
  { word: 'wintry', phonetic: '', meaning: '冬天般的' },
  { word: 'spell', phonetic: '', meaning: '意味着' },
  { word: 'muggy', phonetic: '', meaning: '闷热的' },
  { word: 'precipitation', phonetic: '', meaning: '雨量' },
  { word: 'accountant', phonetic: '', meaning: '会计(员), 会计师' },
  { word: 'audit', phonetic: '', meaning: '审计, 稽核, 查帐vt.稽核, 旁听vi.查账' },
  { word: 'auditor', phonetic: '', meaning: '审计员, 核数师' },
  { word: 'transaction', phonetic: '', meaning: '交易' },
  { word: 'net', phonetic: '', meaning: '净' },
  { word: 'gross', phonetic: '', meaning: '总的 GDP' },
  { word: 'sales', phonetic: '/seɪlz/', meaning: '销售', example: 'Sales have increased by 20% this year.', exampleTranslation: '今年销售额增长了 20%。' },
  { word: 'earning', phonetic: '', meaning: '收益' },
  { word: 'revenue', phonetic: '/ˈrevənuː/', meaning: '收入', example: 'The company revenue increased last quarter.', exampleTranslation: '公司上季度收入增加了。' },
  { word: 'expense', phonetic: '', meaning: '费用' },
  { word: 'pre-tax', phonetic: '', meaning: '税前' },
  { word: 'inventory', phonetic: '', meaning: '库存' },
  { word: 'credit', phonetic: '/ˈkredɪt/', meaning: '信用', example: 'Your credit score is very important.', exampleTranslation: '你的信用评分非常重要。' },
  { word: 'depreciation', phonetic: '', meaning: 'n.贬值, 减价, 跌落, 折旧' },
  { word: 'amortization', phonetic: '', meaning: 'n.摊销,摊还,分期偿付 n.分期偿还' },
  { word: 'asset', phonetic: '', meaning: '资产' },
  { word: 'liability', phonetic: '', meaning: '负债' },
  { word: 'contingency', phonetic: '', meaning: 'n.偶然, 可能性, 意外事故, 可能发生的附带事件' },
  { word: 'undervalue', phonetic: '', meaning: '低估' },
  { word: 'turnover', phonetic: '', meaning: '周转' },
  { word: 'consolidated', phonetic: '', meaning: '加固的； 整理过的； 统一的' },
  { word: 'tax-effect', phonetic: '', meaning: '征税效应' },
  { word: 'quarter', phonetic: '', meaning: '季度' },
  { word: 'term', phonetic: '', meaning: 'n.学期, 期限, 期间, 条款, 条件, 术语' },
  { word: 'financial', phonetic: '', meaning: 'adj.财政的, 金融的' },
  { word: 'budget', phonetic: '', meaning: 'n.预算 vi.做预算, 编入预算' },
  { word: 'profitable', phonetic: '', meaning: 'adj.有利可图的' },
  { word: 'gain', phonetic: '', meaning: 'n.财物的增加, 财富的获取, 利润, 腰槽, 收获' },
  { word: 'overhead', phonetic: '', meaning: '一般管理费用' },
  { word: 'expenditure', phonetic: '', meaning: '支出，经费' },
  { word: 'retrench', phonetic: '', meaning: 'vt.紧缩, 节约, 减少, 删除, 给...筑围墙 vi.紧缩, 节省' },
  { word: 'cost', phonetic: '', meaning: '成本，花费' },
  { word: 'debt', phonetic: '', meaning: 'n.债务, 罪过' },
  { word: 'principal', phonetic: '', meaning: 'n.负责人, 首长, 校长, 主犯, 本金 adj.主要的, 首要的' },
  { word: 'default', phonetic: '', meaning: 'n.默认(值), 缺省(值), 食言, 不履行责任, v.疏怠职责, 缺席, 拖欠, 默认' },
  { word: 'dividend', phonetic: '', meaning: 'n.被除数, 股息, 红利, 额外津贴, 奖金, 年息' },
  { word: 'return', phonetic: '', meaning: '利润' },
  { word: 'angel', phonetic: '', meaning: '个人投资者' },
  { word: 'incubator', phonetic: '', meaning: 'n.培养的器具, 孵卵器, 早产儿保育器' },
  { word: 'corporation', phonetic: '', meaning: '企业' },
  { word: 'enterprise', phonetic: '', meaning: '企业' },
  { word: 'firm', phonetic: '', meaning: '公司' },
  { word: 'headquarters', phonetic: '', meaning: '总部' },
  { word: 'subsidiary', phonetic: '', meaning: '子公司' },
  { word: 'wholly-owned', phonetic: '', meaning: '全资的' },
  { word: 'branch', phonetic: '', meaning: '分部' },
  { word: 'arm', phonetic: '', meaning: '分店，子公司' },
  { word: 'conglomerate', phonetic: '', meaning: '联合体' },
  { word: 'franchiser', phonetic: '', meaning: 'n.经销商, 代销商' },
  { word: 'consortium', phonetic: '', meaning: 'n.社团, 协会, 联盟' },
  { word: 'department', phonetic: '/dɪˈpɑːrtmənt/', meaning: 'n.部, 局, 处, 科, 部门, 系, 学部', example: 'She works in the marketing department.', exampleTranslation: '她在市场部工作。' },
  { word: 'division', phonetic: '', meaning: '部门' },
  { word: 'found', phonetic: '', meaning: 'v.建立, 创立, 创办, 使有根据, 铸造, 熔制' },
  { word: 'establish', phonetic: '', meaning: 'vt.建立, 设立, 安置, 使定居, 使人民接受, 确定 v.建立' },
  { word: 'incorporate', phonetic: '', meaning: 'adj.合并的, 结社的, 一体化的' },
  { word: 'industry', phonetic: '', meaning: 'n.工业, 产业, 行业, 勤奋' },
  { word: 'sector', phonetic: '', meaning: 'n.部分, 部门, [计]扇区, 地区, 象限, 扇形' },
  { word: 'multinational', phonetic: '', meaning: 'adj.多国的, 跨国公司的, 多民族的 n.多国籍公司, 跨国公司' },
  { word: 'expansion', phonetic: '', meaning: 'n.扩充, 开展, 膨胀, 扩张物, 辽阔, 浩瀚' },
  { word: 'leading', phonetic: '', meaning: 'adj.领导的, 第一位的, 最主要的' },
  { word: 'organization', phonetic: '', meaning: 'n.组织, 机构, 团体' },
  { word: 'institution', phonetic: '', meaning: 'n.公共机构, 协会, 制度' },
  { word: 'monopoly', phonetic: '', meaning: 'n.垄断, 垄断者, 专利权, 专利事业' },
  { word: 'advantage', phonetic: '', meaning: 'n.优势, 有利条件, 利益' },
  { word: 'collaboration', phonetic: '', meaning: 'n.协作, 通敌' },
  { word: 'marketing', phonetic: '', meaning: 'n.行销, 买卖' },
  { word: 'range', phonetic: '', meaning: 'n.山脉, 行列, 范围, 射程' },
  { word: 'strategy', phonetic: '', meaning: 'n.策略, 军略' },
  { word: 'tactics', phonetic: '', meaning: 'n.战术, 策略' },
  { word: 'synergy', phonetic: '', meaning: '协同, 配合, 企业合并后的协力优势或协合作用' },
  { word: 'alliance', phonetic: '', meaning: 'n.联盟, 联合' },
  { word: 'takeover', phonetic: '', meaning: 'n. 接收；接管' },
  { word: 'TOB', phonetic: '', meaning: '股票公开买卖' },
  { word: 'MBO', phonetic: '', meaning: '买下产权，买下管理权' },
  { word: 'viable', phonetic: '', meaning: '能养活的, 能生育的, 可行的' },
  { word: 'lucrative', phonetic: '', meaning: '有利的' },
  { word: 'streamline', phonetic: '', meaning: '流线型的' },
  { word: 'realignment', phonetic: '', meaning: '重新排列, 再结盟' },
  { word: 'consolidation', phonetic: '', meaning: '巩固, 合并' },
  { word: 'restructure', phonetic: '', meaning: '更改结构, 重建构造, 调整, 改组' },
  { word: 'spinoff', phonetic: '', meaning: '将子公司股票分配给母公司股东' },
  { word: 'disclosure', phonetic: '', meaning: '揭发, 败露, 败露的事情' },
  { word: 'accountability', phonetic: '', meaning: '有责任, 有义务, 可说明性' },
  { word: 'solvent', phonetic: '', meaning: '溶解的, 有偿付能力的, 有溶解力 n.溶媒, 溶剂, 解决方法' },
  { word: 'ailing', phonetic: '', meaning: '生病的, 境况不佳的' },
  { word: 'commerce', phonetic: '', meaning: '商业' },
  { word: 'performance', phonetic: '', meaning: '履行, 执行, 成绩, 性能, 表演, 演奏' },
  { word: 'chairperson', phonetic: '', meaning: '主席' },
  { word: 'executive', phonetic: '', meaning: '执行者，管理人员' },
  { word: 'controller', phonetic: '', meaning: '管理员, 控制器' },
  { word: 'hierarchy', phonetic: '', meaning: '层次 层级' },
  { word: 'flat', phonetic: '', meaning: '扁平的' },
  { word: 'bureaucracy', phonetic: '', meaning: '官僚, 官僚作风, 官僚机构' },
  { word: 'deputy', phonetic: '', meaning: '代理人, 代表' },
  { word: 'incumbent', phonetic: '', meaning: '职责所在的, 负有...义务的' },
  { word: 'tycoon', phonetic: '', meaning: '企业界大亨, 将军' },
  { word: 'decision-making', phonetic: '', meaning: '决策 决策的' },
  { word: 'shareholder', phonetic: '', meaning: '股东' },
  { word: 'bourse', phonetic: '', meaning: '交易所' },
  { word: 'IPO', phonetic: '', meaning: '首次公开募股' },
  { word: 'Stock', phonetic: '', meaning: '股票' },
  { word: 'share', phonetic: '', meaning: '股份' },
  { word: 'securities', phonetic: '', meaning: '有价证券' },
  { word: 'equities', phonetic: '', meaning: '公平, 公正, 公平的事物, 资产净值, [律]平衡法' },
  { word: 'bond', phonetic: '', meaning: '债券' },
  { word: 'commodities', phonetic: '', meaning: '日用品 期货' },
  { word: 'warrants', phonetic: '', meaning: '授权, 正当理由, 根据, 证明, 凭证, 委任状, 批准, 许可证' },
  { word: 'derivatives', phonetic: '', meaning: '引出的, 系出的' },
  { word: 'futures', phonetic: '', meaning: '期货' },
  { word: 'speculation', phonetic: '', meaning: '思索, 做投机买卖' },
  { word: 'fraud', phonetic: '', meaning: '欺骗, 欺诈行为, 诡计, 骗子, 假货' },
  { word: 'manipulation', phonetic: '', meaning: '处理, 操作, 操纵, 被操纵' },
  { word: 'nosedive', phonetic: '', meaning: '（飞机）俯冲，急降' },
  { word: 'rebound', phonetic: '', meaning: '回弹 v.回弹' },
  { word: 'recover', phonetic: '', meaning: '重新获得, 恢复, 使改过' },
  { word: 'sell-off/dump', phonetic: '', meaning: '倾销，廉价卖光' },
  { word: 'fluctuate', phonetic: '', meaning: '变动, 波动, 涨落, 上下, 动摇 vt.使动摇, 使波动, 使起伏' },
  { word: 'profit-taking', phonetic: '', meaning: '获利了结' },
  { word: 'bull', phonetic: '', meaning: '牛' },
  { word: 'bear', phonetic: '', meaning: '熊' },
  { word: 'erratic', phonetic: '', meaning: '无确定路线, 不稳定的, 奇怪的' },
  { word: 'volatile', phonetic: '', meaning: '飞行的, 挥发性的, 可变的, 不稳定的, 轻快的, 爆炸性的' },
  { word: 'bumpy', phonetic: '', meaning: '颠簸的, 崎岖不平的' },
  { word: 'downturn/upturn', phonetic: '', meaning: '低迷/好转' },
  { word: 'consecutive', phonetic: '', meaning: '连续的, 联贯的' },
  { word: 'paycheck', phonetic: '', meaning: '薪水' },
  { word: 'payroll', phonetic: '', meaning: '薪水册，工资名单' },
  { word: 'remuneration', phonetic: '', meaning: '报酬' },
  { word: 'raise', phonetic: '', meaning: '加薪' },
  { word: 'incentive', phonetic: '', meaning: '动机 激励的' },
  { word: 'award', phonetic: '', meaning: '奖, 奖品 授予, 判给' },
  { word: 'welfare', phonetic: '', meaning: '福利' },
  { word: 'allowance', phonetic: '', meaning: '津贴，补助' },
  { word: 'breakthrough', phonetic: '', meaning: '突破' },
  { word: 'innovation', phonetic: '', meaning: '改革, 创新' },
  { word: 'laboratory', phonetic: '', meaning: '改革, 创新' },
  { word: 'prototype', phonetic: '', meaning: '原型' },
  { word: 'specifications', phonetic: '', meaning: '详述, 规格, 说明书, 规范' },
  { word: 'benchmark', phonetic: '', meaning: '基准' },
  { word: 'patent', phonetic: '', meaning: '专利权, 执照, 专利品' },
  { word: 'royalty', phonetic: '', meaning: '皇室, 王权' },
  { word: 'cutting-edge', phonetic: '', meaning: '最新的，最尖端的' },
  { word: 'sophisticated', phonetic: '', meaning: '诡辩的, 久经世故的' },
  { word: 'ubiquitous', phonetic: '', meaning: '到处存在的, (同时)普遍存在的' },
  { word: 'gadget', phonetic: '', meaning: '小器具, 小配件, 小玩意, 诡计' },
  { word: 'manufacturing', phonetic: '', meaning: '制造业' },
  { word: 'product', phonetic: '/ˈprɑːdʌkt/', meaning: '产品, 产物, 乘积', example: 'This is our latest product.', exampleTranslation: '这是我们的最新产品。' },
  { word: 'output', phonetic: '', meaning: '产量, 输出, 输出量' },
  { word: 'plant', phonetic: '', meaning: '植物, 庄稼, 工厂, 车间, 设备 种植, 栽培, 培养, 安置 种植' },
  { word: 'operation', phonetic: '', meaning: '运转, 操作, 实施, 作用, 业务, 工作, 手术, 军事行动' },
  { word: 'rotation', phonetic: '', meaning: '旋转' },
  { word: 'capacity', phonetic: '', meaning: '容量, 生产量, 容量, 智能, 才能, 能力, 接受力, 地位' },
  { word: 'shortage', phonetic: '', meaning: '不足, 缺乏' },
  { word: 'defective', phonetic: '', meaning: '有缺陷的, (智商或行为有)欠缺的 有缺陷的人, 不完全变化动词' },
  { word: 'lemon', phonetic: '', meaning: '次品' },
  { word: 'facility', phonetic: '', meaning: '容易, 简易, 灵巧, 熟练, 便利, 敏捷, 设备, 工具' },
  { word: 'equipment', phonetic: '', meaning: '装备, 设备, 器材, 装置, 铁道车辆 固定资产, 才能' },
  { word: 'inspection', phonetic: '', meaning: '检查, 视察' },
  { word: 'duplicate', phonetic: '', meaning: '复制品, 副本 复写, 复制, 使加倍, 使成双' },
  { word: 'vendor', phonetic: '', meaning: '卖主' },
  { word: 'supplier', phonetic: '', meaning: '供应者, 补充者, 厂商, 供给者' },
  { word: 'subcontract', phonetic: '', meaning: '转包合同' },
  { word: 'in-house', phonetic: '', meaning: '内部的' },
  { word: 'component', phonetic: '', meaning: '成分 组成的, 构成的' },
  { word: 'module', phonetic: '', meaning: '模数, 模块, 登月舱, 指令舱' },
  { word: 'BTO', phonetic: '', meaning: '订单式生产' },
  { word: 'signature', phonetic: '', meaning: '签名, 署名, 信号' },
  { word: 'seal', phonetic: '', meaning: '封铅, 封条, 印, 图章, 密封 封, 密封 海豹, 海豹毛皮' },
  { word: 'breach', phonetic: '', meaning: '违背, 破坏, 破裂, 裂口 打破, 突破' },
  { word: 'secure', phonetic: '', meaning: '安全的, 可靠的, 放心的, 无虑的' },
  { word: 'draft', phonetic: '', meaning: '草稿, 草案, 草图 起草, 为...打样, 设计' },
  { word: 'agreement', phonetic: '', meaning: '同意, 一致, 协定, 协议' },
  { word: 'statutory', phonetic: '', meaning: '法令的, 法定的' },
  { word: 'execute', phonetic: '', meaning: '执行, 实行, 完成, 处死, 制成, [律]经签名盖章等手续使(证书)生效' },
  { word: 'obligation', phonetic: '', meaning: '义务, 职责, 债务' },
  { word: 'restrict', phonetic: '', meaning: '限制, 约束, 限定' },
  { word: 'disclose', phonetic: '', meaning: '揭露, 透露' },
  { word: 'exclusive', phonetic: '', meaning: '排外的, 孤高的, 唯我独尊的, 独占的, 唯一的, 高级的' },
  { word: 'said', phonetic: '', meaning: '上述的 said item said person' },
  { word: 'shall/may', phonetic: '', meaning: '将/会' },
  { word: 'licensor', phonetic: '', meaning: '认可证颁发者' },
  { word: 'liable', phonetic: '', meaning: '有责任的, 有义务的, 负有责任的' },
  { word: 'settlement', phonetic: '', meaning: '沉降, 解决, 结算, 殖民, 殖民地' },
  { word: 'Passenger', phonetic: '', meaning: '乘客, 旅客' },
  { word: 'fasten', phonetic: '', meaning: '扎牢, 扣住, 闩住, 拴紧, 使固定, 系, 集中于, 强加于 扣紧, 抓住' },
  { word: 'refreshments', phonetic: '', meaning: '点心, 饮料, 精力恢复, 爽快' },
  { word: 'turbulence', phonetic: '', meaning: '骚乱, 动荡, (液体或气体的)紊乱' },
  { word: 'headset', phonetic: '', meaning: '戴在头上的耳机或听筒' },
  { word: 'blanket', phonetic: '', meaning: '毯子 覆盖' },
  { word: 'toiletries', phonetic: '', meaning: '化妆品' },
  { word: 'board', phonetic: '', meaning: '登机' },
  { word: 'stub', phonetic: '', meaning: '存根' },
  { word: 'destination', phonetic: '', meaning: '目的地, [计] 目的文件, 目的单元格' },
  { word: 'stopover', phonetic: '', meaning: '中途停留' },
  { word: 'runway', phonetic: '', meaning: '飞机跑道, 斜坡跑道, 河道' },
  { word: 'departure/arrival', phonetic: '', meaning: '启程/到达' },
  { word: 'disembarkation', phonetic: '', meaning: '起岸, 登陆' },
  { word: 'immigration', phonetic: '', meaning: '外来的移民, 移居入境' },
  { word: 'quarantine', phonetic: '', meaning: '检疫, 隔离, (政治或商业上的)封锁, 检疫期间 检疫, 使在政治或商业上孤立' },
  { word: 'carousel', phonetic: '', meaning: '喧闹的酒会' },
  { word: 'duty-free', phonetic: '', meaning: '免税的' },
  { word: 'fare', phonetic: '', meaning: '费用, 旅客, 食物' },
  { word: 'souvenir', phonetic: '', meaning: '纪念品' },
  { word: 'embassy', phonetic: '', meaning: '大使及其随员, 大使的派遣, 大使馆' },
  { word: 'consulate', phonetic: '', meaning: '领事, 领事馆, 领事任期, 领事的职位、权力和职责' },
  { word: 'expatriate', phonetic: '', meaning: '逐出国外, 脱离国籍, 放逐 移居国外 亡命国外者' },
  { word: 'accommodations', phonetic: '', meaning: '住处, 膳宿' },
  { word: 'concierge', phonetic: '', meaning: '看门人, 门房' },
  { word: 'semiconductor', phonetic: '', meaning: '半导体' },
  { word: 'material', phonetic: '', meaning: '材料, 原料, 物资, 素材, 布料' },
  { word: 'machinery', phonetic: '', meaning: '机器, 机械' },
  { word: 'advertising', phonetic: '/ˈædvərtaɪzɪŋ/', meaning: 'n.广告业,广告adj.广告的', example: 'Advertising is essential for business growth.', exampleTranslation: '广告对业务增长至关重要。' },
  { word: 'amusement/entertainment', phonetic: '', meaning: 'n.娱乐,消遣,娱乐活动' },
  { word: 'insurance', phonetic: '', meaning: 'n.保险,保险单,保险业,保险费' },
  { word: 'healthcare', phonetic: '', meaning: 'n.卫生保健' },
  { word: 'automotive', phonetic: '', meaning: '汽车的, 自动推进的' },
  { word: 'aerospace', phonetic: '', meaning: '航空宇宙' },
  { word: 'construction', phonetic: '', meaning: '建筑, 建筑物, 解释, 造句' },
  { word: 'chemical', phonetic: '', meaning: '化学的 化学制品, 化学药品 化学药品' },
  { word: 'petroleum', phonetic: '', meaning: '石油' },
  { word: 'pharmaceutical', phonetic: '', meaning: '药物 制药(学)上的' },
  { word: 'cosmetics', phonetic: '', meaning: '化妆品 化妆用的' },
  { word: 'beverage', phonetic: '', meaning: '饮料' },
  { word: 'distiller', phonetic: '', meaning: '蒸馏酒者, 蒸馏器' },
  { word: 'retail', phonetic: '', meaning: '零售' },
  { word: 'logistics', phonetic: '', meaning: '后勤学, 后勤' },
  { word: 'telecommunication', phonetic: '', meaning: '电讯, 长途通讯, 无线电通讯, 电信学' },
  { word: 'publishing', phonetic: '', meaning: '出版的, 出版业的' },
  { word: 'fishery', phonetic: '', meaning: 'n.渔业,水产业,渔场,养鱼术' },
  { word: 'forestry', phonetic: '', meaning: 'n.林产,森林地,林学' },
  { word: 'agro-industry', phonetic: '', meaning: 'n.(化肥制造、仓库建筑等)农用工业' },
  { word: 'overpass', phonetic: '', meaning: '<美>天桥, 陆桥 胜过, 通过, 忽视' },
  { word: 'median', phonetic: '', meaning: '中间隔离带' },
  { word: 'detour', phonetic: '', meaning: '绕路' },
  { word: 'crosswalk', phonetic: '', meaning: '人行横道(供行人穿越道路用)' },
  { word: 'unleaded', phonetic: '', meaning: '无铅的，不含铅的（汽油）' },
  { word: 'jammed', phonetic: '', meaning: '挤进, 使塞满, 混杂, 压碎, 使堵塞 堵塞, 轧住, 拥挤' },
  { word: 'bumper-to-bumper', phonetic: '', meaning: '一辆接一辆的' },
  { word: 'vehicle', phonetic: '', meaning: '交通工具, 车辆, 媒介物, 传达手段' },
  { word: 'automobile', phonetic: '', meaning: '交通工具, 车辆, 媒介物, 传达手段' },
  { word: 'pick-up', phonetic: '', meaning: '提取, 搭便车' },
  { word: 'SUV', phonetic: '', meaning: '越野车' },
  { word: 'transmission', phonetic: '', meaning: '播送, 发射, 传动, 传送, 传输, 转播' },
  { word: 'windshield', phonetic: '', meaning: '挡风玻璃' },
  { word: 'horn', phonetic: '', meaning: '喇叭' },
  { word: 'fuel-cell-powered', phonetic: '', meaning: '以燃料电池为电源的' },
  { word: 'hybrid', phonetic: '', meaning: '杂种, 混血儿, 混合物 混合的, 杂种的' },
  { word: 'mileage', phonetic: '', meaning: '英里数, 英里里程' },
  { word: 'skid', phonetic: '', meaning: '刹车' },
  { word: 'speeding', phonetic: '', meaning: '超速行驶' },
  { word: 'collision', phonetic: '', meaning: '碰撞, 冲突' },
  { word: 'rollover', phonetic: '', meaning: '翻车' },
  { word: 'hit-and-run', phonetic: '', meaning: '肇事逃逸' },
  { word: 'premium', phonetic: '', meaning: '额外费用, 奖金, 奖赏, 保险费, (货币兑现的)贴水' },
  { word: 'coverage', phonetic: '', meaning: '覆盖' },
  { word: 'contribution', phonetic: '', meaning: '捐献, 贡献, 投稿' },
  { word: 'insurer', phonetic: '', meaning: '保险业者, 保险公司' },
  { word: 'insured', phonetic: '', meaning: '被保险者, 保户 加入保险的' },
  { word: 'recipient', phonetic: '', meaning: '接受方' },
  { word: 'paid-up', phonetic: '', meaning: '已付的' },
  { word: 'policy', phonetic: '', meaning: '政策, 方针' },
  { word: 'certificate', phonetic: '', meaning: '证书, 证明书 发给证明书, 以证书形式授权给...' },
  { word: 'spouse', phonetic: '', meaning: '配偶(指夫或妻)' },
  { word: 'dependent', phonetic: '', meaning: '依靠的, 依赖的, 由...决定的, 随...而定的' },
  { word: 'deduction', phonetic: '', meaning: '减除, 扣除, 减除额, 推论, 演绎' },
  { word: '401', phonetic: '', meaning: '401企业年金制度' },
  { word: 'spams', phonetic: '', meaning: '垃圾邮件' },
  { word: 'tag-line', phonetic: '', meaning: '收尾语' },
  { word: 'high-profile', phonetic: '', meaning: '高调' },
  { word: 'recognition', phonetic: '', meaning: '赞誉, 承认, 重视, 公认, 赏识 识别' },
  { word: 'awareness', phonetic: '', meaning: '知道, 晓得' },
  { word: 'attractive', phonetic: '', meaning: '吸引人的, 有魅力的' },
  { word: 'display', phonetic: '', meaning: '陈列, 展览, 显示 陈列, 展览, 显示 显示,显示器' },
  { word: 'session', phonetic: '', meaning: '说明会' },
  { word: 'survey', phonetic: '', meaning: '测量, 调查, 俯瞰, 概观, 纵览, 视察' },
  { word: 'questionnaire', phonetic: '', meaning: '调查表, 问卷' },
  { word: 'respondent', phonetic: '', meaning: '回答的 回答者' },
  { word: 'differentiation', phonetic: '', meaning: '区别' },
  { word: 'upstream', phonetic: '', meaning: '向上游, 溯流, 逆流地 溯流而上的' },
  { word: 'CS', phonetic: '', meaning: '消费者满意度' },
  { word: 'client', phonetic: '', meaning: '顾客, 客户, 委托人' },
  { word: 'niche', phonetic: '', meaning: '二手市场' },
  { word: 'cannibalize', phonetic: '', meaning: '吃同类的肉, 拆用...的配件, 调拨...的人员' },
  { word: 'brand', phonetic: '/brænd/', meaning: '商标, 牌子, 烙印 打火印, 污辱', example: 'Our brand is well-known worldwide.', exampleTranslation: '我们的品牌世界闻名。' },
  { word: 'generic', phonetic: '', meaning: '属的, 类的, 一般的, 普通的, 非特殊的' },
  { word: 'maturity', phonetic: '', meaning: '成热, 完备, (票据)到期, 成熟' },
  { word: 'saturation', phonetic: '', meaning: '饱和(状态), 浸润, 浸透 饱和度' },
  { word: 'competitor', phonetic: '/kəmˈpetɪtər/', meaning: '竞争者', example: 'Our main competitor lowered their prices.', exampleTranslation: '我们的主要竞争对手降低了价格。' },
  { word: 'merchandize', phonetic: '', meaning: '商品, 货物' },
  { word: 'high-end/low-end', phonetic: '', meaning: '高端/低端' },
  { word: 'middle-range', phonetic: '', meaning: '中等' },
  { word: 'affordable', phonetic: '', meaning: '提供, 给予, 供应得起' },
  { word: 'authentic', phonetic: '', meaning: '可信的' },
  { word: 'discount', phonetic: '', meaning: '折扣' },
  { word: 'rebate', phonetic: '', meaning: '回扣' },
  { word: 'coupon', phonetic: '', meaning: '优惠券' },
  { word: 'undercut', phonetic: '', meaning: '廉价出售' },
  { word: 'checkout', phonetic: '', meaning: '检验' },
  { word: 'due', phonetic: '', meaning: '应付款' },
  { word: 'acceptable', phonetic: '', meaning: '可接受的, 合意的' },
  { word: 'voucher', phonetic: '', meaning: '证人, 保证人, 证明者, 凭证, 凭单, <美>优惠购货卷' },
  { word: 'surcharge', phonetic: '', meaning: '超载, 追加罚款, 额外费 使装载过多, 追加罚款' },
  { word: 'fast-moving', phonetic: '', meaning: '移动迅速的, 情节紧凑动人的' },
  { word: 'brand-new', phonetic: '', meaning: '新品' },
  { word: 'leading-edge', phonetic: '', meaning: '最新品' },
  { word: 'hip', phonetic: '', meaning: '流行的' },
  { word: 'telemarketing', phonetic: '', meaning: '电话销售,电话推销' },
  { word: 'wholesale', phonetic: '', meaning: '批发, 趸售 批发的, [喻] 大规模的' },
  { word: 'reseller', phonetic: '', meaning: '再卖, 转售' },
  { word: 'outlet', phonetic: '', meaning: '出口, 出路' },
  { word: 'clientele', phonetic: '', meaning: '客户' },
  { word: 'durables', phonetic: '', meaning: '耐用品' },
  { word: 'freebie', phonetic: '', meaning: '免费赠品(尤指戏院赠券)' },
  { word: 'Confirm', phonetic: '', meaning: '确定, 批准, 使巩固, 使有效 v.确认, (基督教中)给...行按手礼' },
  { word: 'outline', phonetic: '', meaning: '大纲, 轮廓, 略图, 外形, 要点, 概要 描画轮廓, 略述' },
  { word: 'suggest', phonetic: '', meaning: '建议, 提出, 使想起, 暗示' },
  { word: 'propose', phonetic: '', meaning: '计划, 建议, 向...提议, 求(婚) 打算, 求婚' },
  { word: 'concede', phonetic: '', meaning: '勉强, 承认, 退让 让步' },
  { word: 'negotiable', phonetic: '', meaning: '可通过谈判解决的' },
  { word: 'quotation', phonetic: '', meaning: '引用语, 价格, 报价单, 行情表' },
  { word: 'estimate', phonetic: '', meaning: '引用语, 价格, 报价单, 行情表' },
  { word: 'specify', phonetic: '', meaning: '指定, 详细说明, 列入清单' },
  { word: 'quantity', phonetic: '', meaning: '量, 数量' },
  { word: 'tentative', phonetic: '', meaning: '试验, 假设 试验性的, 试探的, 尝试的, 暂定的' },
  { word: 'warranty', phonetic: '', meaning: '理由, 根据, 授权, 担保, 保证, 根据' },
  { word: 'guarantee', phonetic: '', meaning: '保证, 保证书, 担保, 抵押品 保证, 担保' },
  { word: 'defect', phonetic: '', meaning: '过失, 缺点' },
  { word: 'flaw', phonetic: '', meaning: '缺点, 裂纹, 瑕疵, 一阵狂风 使破裂, 使有缺陷, 使无效' },
  { word: 'imperfection', phonetic: '', meaning: '不完整性, 非理想性' },
  { word: 'inconvenience', phonetic: '', meaning: '麻烦, 不方便之处' },
  { word: 'intact', phonetic: '', meaning: '完整无缺的' },
  { word: 'cause', phonetic: '', meaning: '引起, 惹起, 使(发生), 促成' },
  { word: 'recall', phonetic: '', meaning: '回忆, 回想, 记起, 取消 召回' },
  { word: 'complaint', phonetic: '', meaning: '诉苦, 抱怨, 牢骚, 委屈, 疾病' },
  { word: 'inquiry', phonetic: '', meaning: '质询, 调查' },
  { word: 'dissatisfied', phonetic: '', meaning: '不满意的, 不高兴的' },
  { word: 'purchaser', phonetic: '', meaning: '买方, 购买者' },
  { word: 'receipt', phonetic: '', meaning: '收据' },
  { word: 'one-stop', phonetic: '', meaning: '一站式服务' },
  { word: 'upgrade', phonetic: '', meaning: '升级' },
  { word: 'customize', phonetic: '', meaning: '定制化，用户化' },
  { word: 'partition', phonetic: '', meaning: '分区' },
  { word: 'reinstall', phonetic: '', meaning: '重新安装' },
  { word: 'reconfigure', phonetic: '', meaning: '重新设置' },
  { word: 'delete', phonetic: '', meaning: '删除' },
  { word: 'save', phonetic: '', meaning: '保存' },
  { word: 'reboot', phonetic: '', meaning: '重启（机器）' },
  { word: 'embed', phonetic: '', meaning: '嵌入、插入' },
  { word: 'archive', phonetic: '', meaning: '存档 档案文件' },
  { word: 'activate', phonetic: '', meaning: '激活' },
  { word: 'compress', phonetic: '', meaning: '压缩, 摘要叙述' },
  { word: 'optimize', phonetic: '', meaning: '使最优化' },
  { word: 'initialize', phonetic: '', meaning: '初始化' },
  { word: 'icon', phonetic: '', meaning: '图标, 肖像, 偶像' },
  { word: 'column', phonetic: '', meaning: '列' },
  { word: 'subtract', phonetic: '', meaning: '减' },
  { word: 'justify', phonetic: '', meaning: '验证' },
  { word: 'indent', phonetic: '', meaning: '缩进' },
  { word: 'space', phonetic: '', meaning: '空格' },
  { word: 'font', phonetic: '', meaning: '字体, 字形, 洗礼盘, 泉, 圣水器' },
  { word: 'peripheral', phonetic: '', meaning: '外围的 外围设备' },
  { word: 'storage', phonetic: '', meaning: '存储' },
  { word: 'removable', phonetic: '', meaning: '可移动的' },
  { word: 'plug-in', phonetic: '', meaning: '插件' },
  { word: 'suite', phonetic: '', meaning: '随员, 家具, 套房, 套, 组, 组曲' },
  { word: 'appointment', phonetic: '', meaning: '约会，约定' },
  { word: 'attendance', phonetic: '', meaning: '出席人数；出席' },
  { word: 'cabinet', phonetic: '', meaning: '橱柜' },
  { word: 'calendar', phonetic: '', meaning: '日历；月历；行事历' },
  { word: 'clerk', phonetic: '', meaning: '办事员，书记' },
  { word: 'directory', phonetic: '', meaning: '人名住址薄' },
  { word: 'filing', phonetic: '', meaning: '归档' },
  { word: 'in-tray', phonetic: '', meaning: '待处理文件盒' },
  { word: 'monitor', phonetic: '', meaning: '检测；监视；追踪' },
  { word: 'out-tray', phonetic: '', meaning: '已处理文件盒' },
  { word: 'postage', phonetic: '', meaning: '邮费' },
  { word: 'punctualit', phonetic: '', meaning: '准时；守时' },
  { word: 'schedule', phonetic: '/ˈskedʒuːl/', meaning: '时间表；计划表', example: 'The meeting is on schedule.', exampleTranslation: '会议按计划进行。' },
  { word: 'shift', phonetic: '', meaning: '换班；轮班；值班' },
  { word: 'staff', phonetic: '', meaning: '全体职员' },
  { word: 'strike', phonetic: '', meaning: '罢工' },
  { word: 'task', phonetic: '', meaning: '工作，任务' },
  { word: 'assignment', phonetic: '', meaning: '分配；工作，分派' },
  { word: 'bulletin', phonetic: '', meaning: '公报；告示；定期报告书' },
  { word: 'calculator', phonetic: '', meaning: '计算器' },
  { word: 'colleague', phonetic: '/ˈkɑːliːɡ/', meaning: '同事，同僚', example: 'My colleagues are very helpful.', exampleTranslation: '我的同事们很乐于助人。' },
  { word: 'document', phonetic: '/ˈdɑːkjumənt/', meaning: '文件，证件', example: 'Please sign this document.', exampleTranslation: '请签署这份文件。' },
  { word: 'extension', phonetic: '', meaning: '分机（电话）；延期' },
  { word: 'intercom', phonetic: '', meaning: '对讲机' },
  { word: 'memo', phonetic: '', meaning: '便条；便笺；备忘录' },
  { word: 'operator', phonetic: '', meaning: '接线生' },
  { word: 'overtime', phonetic: '', meaning: '加班的时间' },
  { word: 'portfolio', phonetic: '', meaning: '作品夹，公事包' },
  { word: 'receptionist', phonetic: '', meaning: '接待员' },
  { word: 'secretary', phonetic: '', meaning: '秘书' },
  { word: 'shorthand', phonetic: '', meaning: '速记，速记法' },
  { word: 'stapler', phonetic: '', meaning: '订书机' },
  { word: 'tardy', phonetic: '', meaning: '迟缓；迟到的；迟延的' },
  { word: 'typist', phonetic: '', meaning: '打字员' },
  { word: 'xerox', phonetic: '', meaning: '影印' },
  { word: 'allocate', phonetic: '', meaning: '拨出；分配；配置' },
  { word: 'applicant', phonetic: '/ˈæplɪkənt/', meaning: '申请人', example: 'There were over 100 applicants for the job.', exampleTranslation: '有超过 100 人申请这份工作。' },
  { word: 'authorize', phonetic: '', meaning: '授权；委托' },
  { word: 'capability', phonetic: '', meaning: '能力；才干；潜力；性能' },
  { word: 'consultation', phonetic: '', meaning: '咨询；商量；商议；会议' },
  { word: 'eligible', phonetic: '', meaning: '合格的，合适的' },
  { word: 'income', phonetic: '', meaning: '收入或所得' },
  { word: 'part-time', phonetic: '', meaning: '兼任的；兼职的' },
  { word: 'permanent', phonetic: '', meaning: '不变的，永久的' },
  { word: 'promote', phonetic: '', meaning: '升迁；促销' },
  { word: 'recruit', phonetic: '/rɪˈkruːt/', meaning: '吸收；征募', example: 'The company is recruiting new staff members.', exampleTranslation: '公司正在招聘新员工。' },
  { word: 'resume', phonetic: '/ˈrezjumeɪ/', meaning: '履历表', example: 'Please send your resume to our HR department.', exampleTranslation: '请将你的简历发送到我们的人力资源部。' },
  { word: 'salary', phonetic: '', meaning: '薪水' },
  { word: 'amateur', phonetic: '', meaning: '业余技术家；外行人；非专家' },
  { word: 'appoint', phonetic: '', meaning: '任命；指定' },
  { word: 'benefit', phonetic: '', meaning: '有益于；受益' },
  { word: 'candidate', phonetic: '/ˈkændɪdət/', meaning: '候选人', example: 'We interviewed three candidates for the position.', exampleTranslation: '我们面试了三位这个职位的候选人。' },
  { word: 'competent', phonetic: '', meaning: '有能力的，胜任的' },
  { word: 'coordinate', phonetic: '', meaning: '协调；调整' },
  { word: 'deadline', phonetic: '/ˈdedlaɪn/', meaning: '截至期限', example: 'The deadline for the project is next Friday.', exampleTranslation: '项目的截止日期是下周五。' },
  { word: 'evaluation', phonetic: '', meaning: '评价；估价' },
  { word: 'expertise', phonetic: '', meaning: '专门技术或知识' },
  { word: 'interview', phonetic: '/ˈɪntərvjuː/', meaning: '会面；面谈', example: 'She has a job interview tomorrow morning.', exampleTranslation: '她明天早上有个面试。' },
  { word: 'novice', phonetic: '', meaning: '生手；新手；初学者' },
  { word: 'pension', phonetic: '', meaning: '养老金；退休金' },
  { word: 'personnel', phonetic: '', meaning: '全体人员；人事部门' },
  { word: 'recommendation', phonetic: '', meaning: '推荐；推荐书；劝告' },
  { word: 'resign', phonetic: '', meaning: '辞职' },
  { word: 'retire', phonetic: '', meaning: '退休' },
  { word: 'substitute', phonetic: '', meaning: '代理人；代用品' },
  { word: 'accrue', phonetic: '', meaning: '产生；增加' },
  { word: 'acquisition', phonetic: '', meaning: '获得；习得' },
  { word: 'amplify', phonetic: '', meaning: '放大；加强；扩展' },
  { word: 'cutback', phonetic: '', meaning: '减少；取消' },
  { word: 'equity', phonetic: '', meaning: '公平；公正；扣除抵押、税金后的剩余财产价值' },
  { word: 'financier', phonetic: '', meaning: '财政家；金融业者；资本家；投资者' },
  { word: 'franchise', phonetic: '', meaning: '经销权；加盟权' },
  { word: 'phase', phonetic: '', meaning: '阶段' },
  { word: 'profile', phonetic: '', meaning: '侧面象；略转；引人瞩目的状态' },
  { word: 'proposition', phonetic: '', meaning: '提案；建议；计划' },
  { word: 'prospectus', phonetic: '', meaning: '计划书；说明书；慕股书' },
  { word: 'rival', phonetic: '', meaning: '竞争者；对手；匹敌者；势均力敌者 竞争的' },
  { word: 'acquire', phonetic: '', meaning: '获得' },
  { word: 'affiliate', phonetic: '', meaning: '支部；分会；子公司' },
  { word: 'assess', phonetic: '', meaning: '评估（财产价值）；评定' },
  { word: 'embezzle', phonetic: '', meaning: '盗用；挪用；侵占（公款等）' },
  { word: 'entrepreneur', phonetic: '', meaning: '企业家；主办人' },
  { word: 'expand', phonetic: '', meaning: '扩张；扩大' },
  { word: 'integrate', phonetic: '', meaning: '统合；整合' },
  { word: 'merger', phonetic: '', meaning: '合并；并吞' },
  { word: 'pending', phonetic: '', meaning: '未决定的；待决定的；即将发生' },
  { word: 'prosperity', phonetic: '', meaning: '繁荣；成功；兴隆' },
  { word: 'scheme', phonetic: '', meaning: '计划；设计；图谋' },
  { word: 'thrive', phonetic: '', meaning: '茂盛；兴旺；繁荣' },
  { word: 'balance', phonetic: '/ˈbæləns/', meaning: '余额；差额', example: 'Please check your account balance.', exampleTranslation: '请查看你的账户余额。' },
  { word: 'deficit', phonetic: '', meaning: '赤字；亏损额' },
  { word: 'devaluation', phonetic: '', meaning: '贬值' },
  { word: 'endorse', phonetic: '', meaning: '赞同；支持；签名；背书' },
  { word: 'exempt', phonetic: '', meaning: '被免除的；豁免的' },
  { word: 'fluctuation', phonetic: '', meaning: '波动；起伏；涨落' },
  { word: 'inflation', phonetic: '', meaning: '物价飞涨；通货膨胀' },
  { word: 'overdraft', phonetic: '', meaning: '透支；透支额' },
  { word: 'profit', phonetic: '', meaning: '利润；收益；营利' },
  { word: 'bankrupt', phonetic: '', meaning: '破产的；倒闭的' },
  { word: 'capital', phonetic: '', meaning: '资金；资本' },
  { word: 'convert', phonetic: '', meaning: '转换；改变' },
  { word: 'currency', phonetic: '', meaning: '货币；流通；通用' },
  { word: 'deposit', phonetic: '/dɪˈpɑːzɪt/', meaning: '付押金；付保证金', example: 'I would like to deposit some money.', exampleTranslation: '我想存一些钱。' },
  { word: 'depression', phonetic: '', meaning: '不景气；忧伤；消沉；沮丧' },
  { word: 'discrepancy', phonetic: '', meaning: '差异；不同；不一致' },
  { word: 'fiscal', phonetic: '', meaning: '财政的；会计的' },
  { word: 'fund', phonetic: '', meaning: '基金；专款' },
  { word: 'holding', phonetic: '', meaning: '土地；财产（常用复数）' },
  { word: 'ledger', phonetic: '', meaning: '总帐；分类帐' },
  { word: 'overdue', phonetic: '', meaning: '过期未付的' },
  { word: 'stockbroker', phonetic: '', meaning: '证券和股票经纪人' },
  { word: 'yield', phonetic: '', meaning: '(1)生产量；收益(2)生产；产生' },
  { word: 'bid', phonetic: '', meaning: '出价；投标；喊价' },
  { word: 'commercial', phonetic: '', meaning: '商业化；商用的；营利的' },
  { word: 'consolidate', phonetic: '', meaning: '结合；合并；强化；巩固' },
  { word: 'corporate', phonetic: '', meaning: '全体的；团体的；公司的；法人的' },
  { word: 'credible', phonetic: '', meaning: '可信的；可靠的' },
  { word: 'debit', phonetic: '', meaning: '借方；借项' },
  { word: 'earnings', phonetic: '', meaning: '薪水；工资；收益' },
  { word: 'export', phonetic: '', meaning: '输出；出口' },
  { word: 'haggle', phonetic: '', meaning: '讨价还价' },
  { word: 'import', phonetic: '', meaning: '输入；进口' },
  { word: 'invoice', phonetic: '', meaning: '发票；发货清单；完成工作的清单（明列数量和价钱）' },
  { word: 'long-range', phonetic: '', meaning: '长期的；远程的' },
  { word: 'payment', phonetic: '/ˈpeɪmənt/', meaning: '支付；付款', example: 'Payment is due at the end of the month.', exampleTranslation: '付款截止日期是月底。' },
  { word: 'quote', phonetic: '', meaning: '报价' },
  { word: 'supply', phonetic: '', meaning: '供应品；供应物；库存' },
  { word: 'tariff', phonetic: '', meaning: '关税' },
  { word: 'commodity', phonetic: '', meaning: '商品；农产品' },
  { word: 'consignee', phonetic: '', meaning: '收件人；受托人' },
  { word: 'consumer', phonetic: '', meaning: '消费者；顾客' },
  { word: 'contractor', phonetic: '', meaning: '立契约人；承包商' },
  { word: 'cost-effective', phonetic: '', meaning: '符合成本效益的' },
  { word: 'dealer', phonetic: '', meaning: '商人；业者' },
  { word: 'forward', phonetic: '', meaning: '送到，转号' },
  { word: 'order', phonetic: '', meaning: '汇单;订货；订单；汇票' },
  { word: 'quota', phonetic: '', meaning: '定量；定额；配额' },
  { word: 'shipment', phonetic: '', meaning: '一批货' },
  { word: 'surplus', phonetic: '', meaning: '(1)过剩的量；盈余(2)过剩的；剩余的' },
  { word: 'trademark', phonetic: '', meaning: '注册商标' },
  { word: 'warehouse', phonetic: '', meaning: '仓库；货价；大商店' },
  { word: 'adjourn', phonetic: '', meaning: '暂时；休会；延期' },
  { word: 'amendment', phonetic: '', meaning: '修正' },
  { word: 'approval', phonetic: '', meaning: '赞成；同意' },
  { word: 'attentive', phonetic: '', meaning: '注意的；留心的专心的' },
  { word: 'brainstorm', phonetic: '', meaning: '脑力激荡，集思广益' },
  { word: 'conference', phonetic: '', meaning: '会议；协商；讨论会' },
  { word: 'convince', phonetic: '', meaning: '使信服' },
  { word: 'cross-reference', phonetic: '', meaning: '前后参照；（使）前后参照' },
  { word: 'delegate', phonetic: '', meaning: '代表' },
  { word: 'demand', phonetic: '', meaning: '要求；强求' },
  { word: 'dispute', phonetic: '', meaning: '争端；争执；纠纷' },
  { word: 'negotiation', phonetic: '', meaning: '协商；谈判' },
  { word: 'persuade', phonetic: '', meaning: '说服；劝服' },
  { word: 'postpone', phonetic: '', meaning: '延迟；延期' },
  { word: 'reconcile', phonetic: '', meaning: '调和；调解' },
  { word: 'agenda', phonetic: '', meaning: '议程' },
  { word: 'announce', phonetic: '', meaning: '通告；宣布；宣告；公诸于众' },
  { word: 'articulate', phonetic: '', meaning: '能清楚有力表达思想感情的；表达能力强的' },
  { word: 'attorney', phonetic: '', meaning: '律师' },
  { word: 'compromise', phonetic: '', meaning: '妥协；折衷；和解' },
  { word: 'consensus', phonetic: '', meaning: '一致的意见；共识' },
  { word: 'converse', phonetic: '', meaning: '谈话；交谈' },
  { word: 'criterion', phonetic: '', meaning: '规范；标准' },
  { word: 'decline', phonetic: '', meaning: '衰落；衰退；下降' },
  { word: 'demonstration', phonetic: '', meaning: '示范；实证；（游行）示威' },
  { word: 'diplomacy', phonetic: '', meaning: '外交手腕；交际手段' },
  { word: 'dissuade', phonetic: '', meaning: '劝阻' },
  { word: 'petition', phonetic: '', meaning: '请愿（书）；请愿' },
  { word: 'premise', phonetic: '', meaning: '前提' },
  { word: 'seminar', phonetic: '', meaning: '研讨会；讨论课；讲习会' },
  { word: 'statement', phonetic: '', meaning: '声明；陈述' },
  { word: 'advance', phonetic: '', meaning: '前进；进展' },
  { word: 'device', phonetic: '', meaning: '装置；设备；图案；设计' },
  { word: 'engineer', phonetic: '', meaning: '工程师' },
  { word: 'facilitate', phonetic: '', meaning: '促进；使（更）容易' },
  { word: 'fuel', phonetic: '', meaning: '燃料' },
  { word: 'generator', phonetic: '', meaning: '发电机；产生器' },
  { word: 'innovative', phonetic: '', meaning: '创新；革新的' },
  { word: 'inventor', phonetic: '', meaning: '发明家' },
  { word: 'malfunction', phonetic: '', meaning: '故障；发生故障，机能失常' },
  { word: 'mode', phonetic: '', meaning: '样式；模式；方式；风尚；时尚' },
  { word: 'operate', phonetic: '', meaning: '操作；运转；经营' },
  { word: 'portable', phonetic: '', meaning: '可携带的；轻便的' },
  { word: 'satellite', phonetic: '', meaning: '卫星' },
  { word: 'specification', phonetic: '', meaning: '说明；详述' },
  { word: 'substandard', phonetic: '', meaning: '标准以下的' },
  { word: 'automaton', phonetic: '', meaning: '自动操作装置；机器人' },
  { word: 'cellphone', phonetic: '', meaning: '移动电话；手机' },
  { word: 'devise', phonetic: '', meaning: '设计；发明；策划' },
  { word: 'hands-on', phonetic: '', meaning: '实地操作的；亲身体验的' },
  { word: 'inspect', phonetic: '', meaning: '检查；审查；视察' },
  { word: 'maintenance', phonetic: '', meaning: '维护；保养' },
  { word: 'manual', phonetic: '', meaning: '使用手册，指南；手工的' },
  { word: 'network', phonetic: '', meaning: '网络系统；广播、电视网；电脑网' },
  { word: 'outage', phonetic: '', meaning: '电力中断；断电' },
  { word: 'procedure', phonetic: '', meaning: '程序；手续' },
  { word: 'reverse', phonetic: '', meaning: '相反的；颠倒的' },
  { word: 'solar', phonetic: '', meaning: '(源自)太阳的；依太阳而运行的' },
  { word: 'static', phonetic: '', meaning: '静电干扰；静止的；静态的；静电的' },
  { word: 'access', phonetic: '', meaning: '进入；接近；使用；取得' },
  { word: 'automatically', phonetic: '', meaning: '无意识的；不自觉的；自动的' },
  { word: 'cable', phonetic: '', meaning: '缆线；电缆' },
  { word: 'compliance', phonetic: '', meaning: '顺从；服从；附和；屈从' },
  { word: 'digital', phonetic: '', meaning: '数位的；数字显示的' },
  { word: 'download', phonetic: '', meaning: '下载' },
  { word: 'hacker', phonetic: '', meaning: '热衷电脑的人，黑客' },
  { word: 'input', phonetic: '', meaning: '输入电脑' },
  { word: 'Internet', phonetic: '', meaning: '国际互联网' },
  { word: 'laptop', phonetic: '', meaning: '笔记本电脑' },
  { word: 'multimedia', phonetic: '', meaning: '多媒体' },
  { word: 'retrieval', phonetic: '', meaning: '取回；恢复' },
  { word: 'state-of-the-art', phonetic: '', meaning: '使用最先进技术的；达到最高水准的' },
  { word: 'terminology', phonetic: '', meaning: '专业术语；专有名词' },
  { word: 'troubleshooting', phonetic: '', meaning: '检修；解决困难的' },
  { word: 'up-to-date', phonetic: '', meaning: '最近的；最新的' },
  { word: 'browse', phonetic: '', meaning: '浏览；随便翻阅' },
  { word: 'command', phonetic: '', meaning: '指令；命令；掌握' },
  { word: 'configuration', phonetic: '', meaning: '结构；构造；配置' },
  { word: 'database', phonetic: '', meaning: '数据库' },
  { word: 'desktop', phonetic: '', meaning: '桌上型的' },
  { word: 'downgrade', phonetic: '', meaning: '降级；使降职' },
  { word: 'floppy', phonetic: '', meaning: '软盘' },
  { word: 'hyperlink', phonetic: '', meaning: '超链接' },
  { word: 'install', phonetic: '', meaning: '安装；安置' },
  { word: 'know-how', phonetic: '', meaning: '技能；专业知识；窍门' },
  { word: 'modern', phonetic: '', meaning: '调制解调器' },
  { word: 'omit', phonetic: '', meaning: '忽略；删除；疏忽' },
  { word: 'scanner', phonetic: '', meaning: '扫描仪' },
  { word: 'server', phonetic: '', meaning: '服务器' },
  { word: 'spreadsheet', phonetic: '', meaning: '电子制表软件；电子表格' },
  { word: 'switch', phonetic: '', meaning: '开关；骤变' },
  { word: 'virus', phonetic: '', meaning: '滤过性病毒；电脑病毒' },
  { word: 'advertisement', phonetic: '', meaning: '广告' },
  { word: 'appendix', phonetic: '', meaning: '附录' },
  { word: 'attach', phonetic: '', meaning: '贴上；附上；附加' },
  { word: 'cohesive', phonetic: '', meaning: '有粘着力的；有结合力的；凝聚性的' },
  { word: 'confidential', phonetic: '', meaning: '秘密的；机密的' },
  { word: 'correspondence', phonetic: '', meaning: '通信；信件' },
  { word: 'dictate', phonetic: '', meaning: '口述；支配；命令' },
  { word: 'elaborate', phonetic: '', meaning: '详尽说明；详尽的；精心制作的' },
  { word: 'inquire', phonetic: '', meaning: '调查；询问' },
  { word: 'leaflet', phonetic: '', meaning: '传单' },
  { word: 'notify', phonetic: '', meaning: '通知；告知' },
  { word: 'publicity', phonetic: '', meaning: '公开；宣传；尽人皆知' },
  { word: 'response', phonetic: '', meaning: '回应' },
  { word: 'revise', phonetic: '', meaning: '修订；修改；校订' },
  { word: 'slogan', phonetic: '', meaning: '口号；标语' },
  { word: 'urgent', phonetic: '', meaning: '紧急的；急迫的' },
  { word: 'affirm', phonetic: '', meaning: '坚称；声明；断言；确认' },
  { word: 'banner', phonetic: '', meaning: '标语；旗帜' },
  { word: 'circular', phonetic: '', meaning: '广告；传单；通告' },
  { word: 'composition', phonetic: '', meaning: '写作；作品；作文；作曲' },
  { word: 'convene', phonetic: '', meaning: '集合；聚集；开会' },
  { word: 'courier', phonetic: '', meaning: '递送急件的信差；邮物专递公司' },
  { word: 'enclose', phonetic: '', meaning: '装入；放入封套' },
  { word: 'inform', phonetic: '', meaning: '通知；告知' },
  { word: 'issue', phonetic: '', meaning: '流出；放出；发行；发布' },
  { word: 'layout', phonetic: '', meaning: '规划；设计；编排' },
  { word: 'legible', phonetic: '', meaning: '（字迹）可以辨认的；易读的' },
  { word: 'proofread', phonetic: '', meaning: '校正；校对' },
  { word: 'regarding', phonetic: '', meaning: '关于；有关' },
  { word: 'restate', phonetic: '', meaning: '再声明；重新叙述；（换一种方式）重说' },
  { word: 'stationery', phonetic: '', meaning: '文具；信纸；信笺' },
  { word: 'write-up', phonetic: '', meaning: '报告书' },
  { word: 'accommodation', phonetic: '', meaning: '适应；住所；膳宿' },
  { word: 'brochure', phonetic: '', meaning: '小册子' },
  { word: 'confirmation', phonetic: '', meaning: '确认' },
  { word: 'customs', phonetic: '', meaning: '海关；关税' },
  { word: 'departure', phonetic: '/dɪˈpɑːrtʃər/', meaning: '离开；出发', example: 'The departure time is 10 AM.', exampleTranslation: '出发时间是上午 10 点。' },
  { word: 'expedition', phonetic: '', meaning: '探险；远征队' },
  { word: 'flight', phonetic: '/flaɪt/', meaning: '飞行；航班；航程', example: 'My flight departs at 6 PM.', exampleTranslation: '我的航班下午 6 点起飞。' },
  { word: 'lodge', phonetic: '', meaning: '小屋；旅馆' },
  { word: 'luxurious', phonetic: '', meaning: '奢华的；非常舒适的' },
  { word: 'motel', phonetic: '', meaning: '汽车旅馆' },
  { word: 'packing', phonetic: '', meaning: '包装；打包' },
  { word: 'reservation', phonetic: '/ˌrezərˈveɪʃn/', meaning: '预约；预订；保留', example: 'I made a hotel reservation.', exampleTranslation: '我预订了酒店。' },
  { word: 'sightseeing', phonetic: '', meaning: '观光；游览' },
  { word: 'valid', phonetic: '', meaning: '依法有效的；有效的' },
  { word: 'breathtaking', phonetic: '', meaning: '惊人的；惊艳的；惊险的' },
  { word: 'carry-on', phonetic: '', meaning: '登机行李；手提行李' },
  { word: 'cruise', phonetic: '', meaning: '乘船游览' },
  { word: 'deluxe', phonetic: '', meaning: '豪华的；高级的' },
  { word: 'exotic', phonetic: '', meaning: '异国风情的；异国的' },
  { word: 'luggage', phonetic: '/ˈlʌɡɪdʒ/', meaning: '行李', example: 'Please collect your luggage.', exampleTranslation: '请领取你的行李。' },
  { word: 'overseas', phonetic: '', meaning: '在海外的，国外的（注意一般使用时都有s）' },
  { word: 'porter', phonetic: '', meaning: '脚夫；门房' },
  { word: 'round-trip', phonetic: '', meaning: '来回的，双程的' },
  { word: 'vacant', phonetic: '', meaning: '空的，未被占用的' },
  { word: 'voyage', phonetic: '', meaning: '旅行；航行' },
  { word: 'accelerate', phonetic: '', meaning: '加速；促进；前进' },
  { word: 'aircraft', phonetic: '', meaning: '飞机；飞行器；航空器' },
  { word: 'arrival', phonetic: '/əˈraɪvl/', meaning: '到达；抵达', example: 'The arrival time is 2 PM.', exampleTranslation: '到达时间是下午 2 点。' },
  { word: 'cargo', phonetic: '', meaning: '货物' },
  { word: 'convertible', phonetic: '', meaning: '敞篷车' },
  { word: 'delay', phonetic: '', meaning: '担搁；延迟' },
  { word: 'forbid', phonetic: '', meaning: '禁止' },
  { word: 'jaywalk', phonetic: '', meaning: '不遵守交通规则穿越马路；闯红灯' },
  { word: 'navigate', phonetic: '', meaning: '航行；驾驶' },
  { word: 'pilot', phonetic: '', meaning: '飞行员' },
  { word: 'route', phonetic: '', meaning: '路径；路线' },
  { word: 'taxicab', phonetic: '', meaning: '计程车' },
  { word: 'acrophobia', phonetic: '', meaning: '恐高症' },
  { word: 'airliner', phonetic: '', meaning: '大型客机' },
  { word: 'aviation', phonetic: '', meaning: '飞行；航空学' },
  { word: 'cabin', phonetic: '', meaning: '小屋；客舱；机舱' },
  { word: 'commuter', phonetic: '', meaning: '通勤者' },
  { word: 'conveyance', phonetic: '', meaning: '运输；交通工具' },
  { word: 'crossroads', phonetic: '', meaning: '十字路口' },
  { word: 'ferry', phonetic: '', meaning: '渡轮' },
  { word: 'freight', phonetic: '', meaning: '货运；货物' },
  { word: 'jeopardy', phonetic: '', meaning: '风险；危险；危难' },
  { word: 'pedestrian', phonetic: '', meaning: '行人；步行者' },
  { word: 'restriction', phonetic: '', meaning: '限制；约束' },
  { word: 'timetable', phonetic: '', meaning: '时间表；时刻表' },
  { word: 'transport', phonetic: '', meaning: '运输；交通工具；运输系' },
  { word: 'via', phonetic: '', meaning: '经由；借由' },
  { word: 'bazaar', phonetic: '', meaning: '市场；集市' },
  { word: 'customer', phonetic: '/ˈkʌstəmər/', meaning: '顾客；客户', example: 'The customer is always right.', exampleTranslation: '顾客永远是对的。' },
  { word: 'distributor', phonetic: '', meaning: '供应商；经销商' },
  { word: 'expiration', phonetic: '', meaning: '终结；期满' },
  { word: 'itemize', phonetic: '', meaning: '详细列举；分条列举' },
  { word: 'latest', phonetic: '', meaning: '最新的' },
  { word: 'pickpocket', phonetic: '', meaning: '扒手' },
  { word: 'pushcart', phonetic: '', meaning: '手推车' },
  { word: 'reimburse', phonetic: '', meaning: '偿还；补偿' },
  { word: 'request', phonetic: '', meaning: '请求；要求' },
  { word: 'sample', phonetic: '', meaning: '样品；样本' },
  { word: 'solicit', phonetic: '', meaning: '请求；恳求；祈求' },
  { word: 'trendy', phonetic: '', meaning: '时髦的；流行的' },
  { word: 'bargain', phonetic: '', meaning: '便宜货；廉价品' },
  { word: 'drugstore', phonetic: '', meaning: '兼卖杂货的药房' },
  { word: 'label', phonetic: '', meaning: '标签；标记' },
  { word: 'modify', phonetic: '', meaning: '修改；变更' },
  { word: 'patron', phonetic: '', meaning: '顾客；赞助人' },
  { word: 'purchase', phonetic: '', meaning: '购买；购得之物' },
  { word: 'refund', phonetic: '', meaning: '退款；退还；赔偿' },
  { word: 'retailer', phonetic: '', meaning: '零售商' },
  { word: 'thrift', phonetic: '', meaning: '节俭；节约' },
  { word: 'vender', phonetic: '', meaning: '小贩' },
  { word: 'workmanship', phonetic: '', meaning: '技巧；手艺' },
  { word: 'alcohol', phonetic: '', meaning: '酒精' },
  { word: 'appetite', phonetic: '', meaning: '胃口，食欲' },
  { word: 'artificial', phonetic: '', meaning: '人造的；仿真的' },
  { word: 'bland', phonetic: '', meaning: '淡而无味的；温和的；无刺激性的' },
  { word: 'chef', phonetic: '', meaning: '主厨；大厨' },
  { word: 'crave', phonetic: '', meaning: '渴望' },
  { word: 'delicacy', phonetic: '', meaning: '佳肴' },
  { word: 'digest', phonetic: '', meaning: '消化' },
  { word: 'fragrant', phonetic: '', meaning: '有香味的；芳香的' },
  { word: 'ingredient', phonetic: '', meaning: '成分；配料；配方' },
  { word: 'liquor', phonetic: '', meaning: '烈酒（如威士忌）' },
  { word: 'munch', phonetic: '', meaning: '用力嚼；大声咀嚼' },
  { word: 'palatable', phonetic: '', meaning: '美味的；顺耳的；怡人的' },
  { word: 'portion', phonetic: '', meaning: '部分；一份' },
  { word: 'ravenous', phonetic: '', meaning: '饥饿的；贪婪的' },
  { word: 'refreshment', phonetic: '', meaning: '茶点' },
  { word: 'silverware', phonetic: '', meaning: '银器；镀银餐具' },
  { word: 'specialty', phonetic: '', meaning: '专攻；专业；专长；特制品' },
  { word: 'starve', phonetic: '', meaning: '饿死；挨饿' },
  { word: 'aperitif', phonetic: '', meaning: '饭前酒' },
  { word: 'appetizer', phonetic: '', meaning: '开胃菜' },
  { word: 'buffet', phonetic: '', meaning: '自助餐' },
  { word: 'chopsticks', phonetic: '', meaning: '筷子' },
  { word: 'cuisine', phonetic: '', meaning: '烹调' },
  { word: 'dessert', phonetic: '', meaning: '餐后甜点' },
  { word: 'entree', phonetic: '', meaning: '主菜' },
  { word: 'leftovers', phonetic: '', meaning: '剩饭剩菜' },
  { word: 'menu', phonetic: '', meaning: '菜单' },
  { word: 'napkin', phonetic: '', meaning: '餐巾' },
  { word: 'parched', phonetic: '', meaning: '焦干的；极渴的' },
  { word: 'pastry', phonetic: '', meaning: '用面团和油酥烤成的小甜点心' },
  { word: 'preservative', phonetic: '', meaning: '防腐剂' },
  { word: 'recipe', phonetic: '', meaning: '食谱；烹饪法；秘诀' },
  { word: 'seasoning', phonetic: '', meaning: '调味品；佐料' },
  { word: 'snack', phonetic: '', meaning: '小吃；点心 吃点心' },
  { word: 'spice', phonetic: '', meaning: '香料；调味品' },
  { word: 'vegetarian', phonetic: '', meaning: '素食者' },
  { word: 'acceptance', phonetic: '', meaning: '接受；赞同' },
  { word: 'acquaintance', phonetic: '', meaning: '相识但是不是很熟的人' },
  { word: 'anniversary', phonetic: '', meaning: '周年纪念日' },
  { word: 'associate', phonetic: '', meaning: '(1)同事；伙伴联想；交往' },
  { word: 'banquet', phonetic: '', meaning: '酒席；正式的宴会' },
  { word: 'commitment', phonetic: '', meaning: '承诺；许诺' },
  { word: 'courtesy', phonetic: '', meaning: '礼貌；礼仪；好意；殷勤' },
  { word: 'distinguished', phonetic: '', meaning: '卓越的；杰出的；著名的' },
  { word: 'embrace', phonetic: '', meaning: '拥抱；围绕；包括' },
  { word: 'etiquette', phonetic: '', meaning: '礼节；规范' },
  { word: 'farewell', phonetic: '', meaning: '一路平安；再见；告别' },
  { word: 'greeting', phonetic: '', meaning: '致敬；问候；（复数）致意；赞词' },
  { word: 'hug', phonetic: '', meaning: '拥抱；紧抱' },
  { word: 'lavish', phonetic: '', meaning: '过分大方的；浪费的；丰富的' },
  { word: 'nosy', phonetic: '', meaning: '好管闲事的；爱打听的' },
  { word: 'offensive', phonetic: '', meaning: '令人不快的；讨厌的；冒犯的' },
  { word: 'protocol', phonetic: '', meaning: '外交礼仪；草约' },
  { word: 'regards', phonetic: '', meaning: '问候；致意' },
  { word: 'salute', phonetic: '', meaning: '向……打招呼；向……行军礼；向……表示敬意' },
  { word: 'acknowledge', phonetic: '', meaning: '承认；承认……之存在、权力；表示感谢' },
  { word: 'aggressive', phonetic: '', meaning: '挑衅的；有侵略性的；有进取心的；积极的' },
  { word: 'apologize', phonetic: '', meaning: '道歉' },
  { word: 'barrier', phonetic: '', meaning: '障碍；障碍物；隔阂' },
  { word: 'compliment', phonetic: '', meaning: '赞扬；恭维' },
  { word: 'criticize', phonetic: '', meaning: '批评；评论' },
  { word: 'eloquent', phonetic: '', meaning: '口才好的；雄辩的' },
  { word: 'encounter', phonetic: '', meaning: '相遇；遭遇 偶然碰见；面临' },
  { word: 'extend', phonetic: '', meaning: '延伸 延续；扩大；延长；给予；提供' },
  { word: 'favorable', phonetic: '', meaning: '令人满意的；博得赞许的；有帮助的；有利的' },
  { word: 'gossip', phonetic: '', meaning: '闲话；流言； 说闲话' },
  { word: 'hilarious', phonetic: '', meaning: '狂欢的；令人捧腹的' },
  { word: 'intrude', phonetic: '', meaning: '闯入；侵入；把……强加诸于' },
  { word: 'modest', phonetic: '', meaning: '谦逊的；适度的；朴实的；端庄的' },
  { word: 'nuisance', phonetic: '', meaning: '讨厌之人、事、物' },
  { word: 'prompt', phonetic: '', meaning: '准时的；按时的；迅速的；立刻行动的' },
  { word: 'quarrel', phonetic: '', meaning: '争吵；争论 吵架' },
  { word: 'scandal', phonetic: '', meaning: '丑闻；引人愤慨之事' },
  { word: 'amuse', phonetic: '', meaning: '使欢乐；使愉快；使发笑' },
  { word: 'audience', phonetic: '', meaning: '听众；观众' },
  { word: 'ballet', phonetic: '', meaning: '芭蕾舞' },
  { word: 'celebrity', phonetic: '', meaning: '名人；名声' },
  { word: 'cinema', phonetic: '', meaning: '电影；影片；电影院；电影艺术；电影业' },
  { word: 'composer', phonetic: '', meaning: '作曲家' },
  { word: 'cue', phonetic: '', meaning: '暗示；提示' },
  { word: 'drama', phonetic: '', meaning: '戏剧；剧本' },
  { word: 'headline', phonetic: '', meaning: '（报纸的）标题' },
  { word: 'newscast', phonetic: '', meaning: '新闻广播' },
  { word: 'periodical', phonetic: '', meaning: '杂志；期刊' },
  { word: 'premiere', phonetic: '', meaning: '首次公演；首映' },
  { word: 'rate', phonetic: '', meaning: '分级；分等' },
  { word: 'scenario', phonetic: '', meaning: '戏剧的情节' },
  { word: 'scriptwriter', phonetic: '', meaning: '剧作家；编剧' },
  { word: 'symphony', phonetic: '', meaning: '交响曲' },
  { word: 'applaud', phonetic: '', meaning: '鼓掌' },
  { word: 'audition', phonetic: '', meaning: '试听；试演' },
  { word: 'broadcast', phonetic: '', meaning: '广播；宣传' },
  { word: 'carnival', phonetic: '', meaning: '狂欢；欢宴；嘉年华会；巡回娱乐表演' },
  { word: 'choreography', phonetic: '', meaning: '舞蹈设计；编舞' },
  { word: 'circus', phonetic: '', meaning: '马戏团' },
  { word: 'concert', phonetic: '', meaning: '音乐会' },
  { word: 'critic', phonetic: '', meaning: '批评家；评论家；吹毛求疵的人' },
  { word: 'editorial', phonetic: '', meaning: '社论' },
  { word: 'finale', phonetic: '', meaning: '结局；乐曲的最后部分' },
  { word: 'media', phonetic: '', meaning: '媒体' },
  { word: 'playwright', phonetic: '', meaning: '剧作家' },
  { word: 'preview', phonetic: '', meaning: '试映；预告片' },
  { word: 'rehearsal', phonetic: '', meaning: '预演；排练' },
  { word: 'screen', phonetic: '', meaning: '隔板；荧幕；荧光屏' },
  { word: 'stunt', phonetic: '', meaning: '特技；噱头' },
  { word: 'theater', phonetic: '', meaning: '戏院；剧院' },
  { word: 'violin', phonetic: '', meaning: '小提琴' },
  { word: 'aerobics', phonetic: '', meaning: '有氧运动' },
  { word: 'coach', phonetic: '', meaning: '教师；教练' },
  { word: 'compete', phonetic: '', meaning: '竞争；比赛' },
  { word: 'defeat', phonetic: '', meaning: '失败；击败' },
  { word: 'fitness', phonetic: '', meaning: '适合；恰当；身体健康' },
  { word: 'gym', phonetic: '', meaning: '健身房；体育馆' },
  { word: 'league', phonetic: '', meaning: '联盟；同盟' },
  { word: 'marathon', phonetic: '', meaning: '马拉松；耐力比赛' },
  { word: 'mountaineering', phonetic: '', meaning: '登山运动' },
  { word: 'participate', phonetic: '', meaning: '参与；参加' },
  { word: 'recreation', phonetic: '', meaning: '娱乐；消遣' },
  { word: 'relaxation', phonetic: '', meaning: '松弛；缓和；休息；娱乐' },
  { word: 'rigor', phonetic: '', meaning: '严格；严苛；艰苦' },
  { word: 'stadium', phonetic: '', meaning: '体育场' },
  { word: 'stroll', phonetic: '', meaning: '散步；闲逛' },
  { word: 'surrender', phonetic: '', meaning: '（向敌人）投降；放弃' },
  { word: 'time-out', phonetic: '', meaning: '暂停' },
  { word: 'trophy', phonetic: '', meaning: '奖品；奖杯；战利品' },
  { word: 'usher', phonetic: '', meaning: '引座员；招待员' },
  { word: 'billiards', phonetic: '', meaning: '撞球' },
  { word: 'combative', phonetic: '', meaning: '好战的；好斗的' },
  { word: 'forfeit', phonetic: '', meaning: '罚款；丧失' },
  { word: 'intensity', phonetic: '', meaning: '强度；强烈' },
  { word: 'leisure', phonetic: '', meaning: '空闲；闲暇时间' },
  { word: 'massage', phonetic: '', meaning: '按摩；揉捏' },
  { word: 'muscle', phonetic: '', meaning: '肌肉；力量' },
  { word: 'pastime', phonetic: '', meaning: '娱乐；消遣' },
  { word: 'referee', phonetic: '', meaning: '裁判员；仲裁者' },
  { word: 'spectator', phonetic: '', meaning: '观众；旁观者' },
  { word: 'stretch', phonetic: '', meaning: '伸张；伸开；伸展' },
  { word: 'tactic', phonetic: '', meaning: '战略；策略（常用复数）' },
  { word: 'tournament', phonetic: '', meaning: '比赛；锦标赛' },
  { word: 'umpire', phonetic: '', meaning: '裁判；仲裁' },
  { word: 'alleviate', phonetic: '', meaning: '减轻；缓和' },
  { word: 'bacteria', phonetic: '', meaning: '细菌' },
  { word: 'compensation', phonetic: '', meaning: '补偿；赔偿；报偿' },
  { word: 'contagious', phonetic: '', meaning: '接触传染的' },
  { word: 'immune', phonetic: '', meaning: '免除的；豁免的；免疫的' },
  { word: 'infection', phonetic: '', meaning: '感染' },
  { word: 'investigator', phonetic: '', meaning: '调查员' },
  { word: 'mandatory', phonetic: '', meaning: '命令的；强制的；义务的' },
  { word: 'option', phonetic: '', meaning: '选择权；选择之自由；可选择的东西' },
  { word: 'outpatient', phonetic: '', meaning: '门诊病人' },
  { word: 'severe', phonetic: '', meaning: '严苛的；严格的；严重的' },
  { word: 'stroke', phonetic: '', meaning: '脑血管破裂或阻塞；中风' },
  { word: 'vital', phonetic: '', meaning: '非常必要的；及其重要的；攸关生死的' },
  { word: 'antibiotic', phonetic: '', meaning: '抗生素' },
  { word: 'commission', phonetic: '', meaning: '佣金' },
  { word: 'comprehensive', phonetic: '', meaning: '全面的；广泛的' },
  { word: 'diagnose', phonetic: '', meaning: '诊断；判断' },
  { word: 'excruciating', phonetic: '', meaning: '极痛苦的；极度的' },
  { word: 'handicap', phonetic: '', meaning: '残障；不利条件；障碍' },
  { word: 'indemnity', phonetic: '', meaning: '损害保障；损害赔偿' },
  { word: 'nutrition', phonetic: '', meaning: '营养之供给或摄取；营养' },
  { word: 'purification', phonetic: '', meaning: '洗净；净化' },
  { word: 'surgery', phonetic: '', meaning: '（外科）手术' },
  { word: 'trauma', phonetic: '', meaning: '外伤；心灵的伤' },
  { word: 'waive', phonetic: '', meaning: '放弃；弃权' },
  { word: 'appliance', phonetic: '', meaning: '设备；器具；工具；家用电器' },
  { word: 'burglar', phonetic: '', meaning: '窃贼；夜间入屋行窃的小偷' },
  { word: 'community', phonetic: '', meaning: '社区' },
  { word: 'electronics', phonetic: '', meaning: '电子学' },
  { word: 'furniture', phonetic: '', meaning: '家具' },
  { word: 'landlord', phonetic: '', meaning: '地主；房东' },
  { word: 'laundry', phonetic: '', meaning: '洗衣店；要洗或已洗好的衣物' },
  { word: 'lease', phonetic: '', meaning: '租约；出租；租用' },
  { word: 'mattress', phonetic: '', meaning: '床垫' },
  { word: 'ornament', phonetic: '', meaning: '装饰品' },
  { word: 'plumbing', phonetic: '', meaning: '水管设施' },
  { word: 'possession', phonetic: '', meaning: '所有；个人财产' },
  { word: 'renovate', phonetic: '', meaning: '更新；修复；恢复' },
  { word: 'rural', phonetic: '', meaning: '乡下；田园' },
  { word: 'suburb', phonetic: '', meaning: '（常用复数）郊区；近郊' },
  { word: 'urban', phonetic: '', meaning: '都市的；都市式的' },
  { word: 'balcony', phonetic: '', meaning: '阳台；包厢' },
  { word: 'chore', phonetic: '', meaning: '家务难事；困难繁琐无趣的工作' },
  { word: 'furnishings', phonetic: '', meaning: '家具；室内陈设' },
  { word: 'garage', phonetic: '', meaning: '车库；修车厂' },
  { word: 'kitchenware', phonetic: '', meaning: '厨房用具' },
  { word: 'laundromat', phonetic: '', meaning: '自助洗衣店' },
  { word: 'lawn', phonetic: '', meaning: '草坪；草地' },
  { word: 'messy', phonetic: '', meaning: '杂乱的；肮脏的' },
  { word: 'neighborhood', phonetic: '', meaning: '街坊；住宅区；临近地区' },
  { word: 'playground', phonetic: '', meaning: '运动场；游戏场；游乐场' },
  { word: 'porch', phonetic: '', meaning: '门廊；游廊' },
  { word: 'relocate', phonetic: '', meaning: '重新安置；迁徙' },
  { word: 'residence', phonetic: '', meaning: '住所；公馆；居住' },
  { word: 'tenant', phonetic: '', meaning: '房客；承租人；佃户' },
  { word: 'utility', phonetic: '', meaning: '公共实业；实用' },
  { word: 'affection', phonetic: '', meaning: '感情；钟爱' },
  { word: 'anticipate', phonetic: '', meaning: '预见；期待；在……之前行动；预先考虑；提前使用' },
  { word: 'brag', phonetic: '', meaning: '自夸；吹嘘' },
  { word: 'delighted', phonetic: '', meaning: '欣喜的；愉快的' },
  { word: 'detest', phonetic: '', meaning: '憎恶；痛恨；嫌恶' },
  { word: 'disgust', phonetic: '', meaning: '作呕；厌恶；反感 导致反感' },
  { word: 'distress', phonetic: '', meaning: '悲痛；贫困；危难' },
  { word: 'enthusiastic', phonetic: '', meaning: '热心的；狂热的' },
  { word: 'esteem', phonetic: '', meaning: '好评；尊敬  极看重；尊重' },
  { word: 'fascination', phonetic: '', meaning: '入迷；着迷；强烈吸引力；魅力' },
  { word: 'gloomy', phonetic: '', meaning: '幽暗的；令人沮丧的；忧郁的；没有希望的' },
  { word: 'impartial', phonetic: '', meaning: '不偏袒；无偏见的；公正的' },
  { word: 'impulsive', phonetic: '', meaning: '冲动的' },
  { word: 'irritated', phonetic: '', meaning: '被激怒的；发炎的；疼痛的' },
  { word: 'mad', phonetic: '', meaning: '发疯的；疯狂的；着迷的；愚蠢的；生气的' },
  { word: 'objective', phonetic: '', meaning: '目标；客观的' },
  { word: 'panic', phonetic: '', meaning: '恐慌；使恐慌' },
  { word: 'prejudice', phonetic: '', meaning: '偏见；歧视' },
  { word: 'repulsive', phonetic: '', meaning: '使人反感的；令人厌恶的' },
  { word: 'tranquility', phonetic: '', meaning: '平静的；安宁' },
  { word: 'ambition', phonetic: '', meaning: '雄心；野心' },
  { word: 'contentment', phonetic: '', meaning: '满意；满足' },
  { word: 'despair', phonetic: '', meaning: '绝望；使人绝望的事物' },
  { word: 'devoted', phonetic: '', meaning: '挚爱的；忠实的；热忱的' },
  { word: 'disposition', phonetic: '', meaning: '倾向；性格；气质；性情' },
  { word: 'elegant', phonetic: '', meaning: '高雅的；有品味的；上等的' },
  { word: 'entice', phonetic: '', meaning: '诱惑；引诱' },
  { word: 'fancy', phonetic: '', meaning: '精心设计的；特技的；花俏的；昂贵的' },
  { word: 'fondness', phonetic: '', meaning: '钟爱；溺爱；嗜好；癖好' },
  { word: 'hideous', phonetic: '', meaning: '丑的吓人；不忍睹的；丑恶的；可憎的' },
  { word: 'impression', phonetic: '', meaning: '意念；印象；不太明确的感觉或想法' },
  { word: 'instinct', phonetic: '', meaning: '天性；本能；直觉' },
  { word: 'jealous', phonetic: '', meaning: '嫉妒的；羡慕的；唯恐失去的' },
  { word: 'nasty', phonetic: '', meaning: '肮脏的；不道德的；恶毒的；令人不愉快的；严重的' },
  { word: 'optimistic', phonetic: '', meaning: '乐观的' },
  { word: 'perceive', phonetic: '', meaning: '感知；察觉；理会' },
  { word: 'provoke', phonetic: '', meaning: '激怒；引起；激起' },
  { word: 'startle', phonetic: '', meaning: '惊吓；使吓一跳' },
  { word: 'upset', phonetic: '', meaning: '使心烦意乱；使不舒服；使失败；打翻' },
  { word: 'aspect', phonetic: '', meaning: '面貌；方向；朝向' },
  { word: 'assumption', phonetic: '', meaning: '假定；假设' },
  { word: 'attempt', phonetic: '', meaning: '⑴企图；攻击 ⑵努力尝试；企图' },
  { word: 'declaration', phonetic: '', meaning: '宣布；公布；宣言' },
  { word: 'endeavor', phonetic: '', meaning: '努力；尽力 试图；尝试' },
  { word: 'exceed', phonetic: '', meaning: '超过；超出；超越' },
  { word: 'identity', phonetic: '', meaning: '身份；本体；相同；同一' },
  { word: 'implication', phonetic: '', meaning: '含义；暗示；牵连' },
  { word: 'inspire', phonetic: '', meaning: '鼓舞；激发；引发' },
  { word: 'intention', phonetic: '', meaning: '意图；目的' },
  { word: 'interrupt', phonetic: '', meaning: '打断；中断' },
  { word: 'manipulate', phonetic: '', meaning: '操作；操纵' },
  { word: 'obstacle', phonetic: '', meaning: '障碍物；阻碍' },
  { word: 'priority', phonetic: '', meaning: '优先权；优先考虑的事' },
  { word: 'prohibit', phonetic: '', meaning: '禁止；防止；阻止' },
  { word: 'reassure', phonetic: '', meaning: '使安心；使放心；使恢复信心；再保证' },
  { word: 'remind', phonetic: '', meaning: '提醒；使想起' },
  { word: 'sustain', phonetic: '', meaning: '维持；持续；支撑；蒙受' },
  { word: 'undertake', phonetic: '', meaning: '承担；许诺；保证' },
  { word: 'alter', phonetic: '', meaning: '改变；修改' },
  { word: 'assurance', phonetic: '', meaning: '保证；担保；自信；把握' },
  { word: 'clarify', phonetic: '', meaning: '澄清；使纯净' },
  { word: 'discard', phonetic: '', meaning: '抛弃；丢弃' },
  { word: 'entitle', phonetic: '', meaning: '定名；使有资格' },
  { word: 'impact', phonetic: '', meaning: '碰撞力；影响；行动' },
  { word: 'instruct', phonetic: '', meaning: '教授；指导；下命令；指示' },
  { word: 'interfere', phonetic: '', meaning: '妨害；扰乱；介入；干涉' },
  { word: 'involve', phonetic: '', meaning: '使卷入；牵涉；伴随（指必然结果）' },
  { word: 'merit', phonetic: '', meaning: '功劳；价值；优点' },
  { word: 'permit', phonetic: '', meaning: '许可证；执照 准许；许可' },
  { word: 'proceed', phonetic: '', meaning: '着手；继续进行' },
  { word: 'register', phonetic: '', meaning: '⑴登记簿；注册簿 ⑵记录；注册；登记姓名' },
  { word: 'risk', phonetic: '', meaning: '风险；危险 使遭受危险；冒……的危险' },
  { word: 'submit', phonetic: '', meaning: '认输；使服从；提出' },
  { word: 'speculate', phonetic: '', meaning: '沉思；思索；猜测；推测；投机' },
  { word: 'verify', phonetic: '', meaning: '证明；证实；确认' },
  { word: 'absurd', phonetic: '', meaning: '荒谬的；不合理的；违反常理的' },
  { word: 'adequate', phonetic: '', meaning: '足够的；适当的' },
  { word: 'ample', phonetic: '', meaning: '广大的；宽敞的；充足的' },
  { word: 'decent', phonetic: '', meaning: '合宜的；得体的；适当的' },
  { word: 'dreadful', phonetic: '', meaning: '令人恐怖的；令人害怕的' },
  { word: 'exceptional', phonetic: '', meaning: '异常的；例外的；特别优秀' },
  { word: 'exquisite', phonetic: '', meaning: '精细的；精美的；敏锐的；细致的' },
  { word: 'farfetched', phonetic: '', meaning: '牵强的；不大可信的；不自然的' },
  { word: 'ingenious', phonetic: '', meaning: '有巧思的；有创意的；灵敏的' },
  { word: 'instant', phonetic: '', meaning: '立即的；（食品）快速方便的' },
  { word: 'legitimate', phonetic: '', meaning: '合法的；正当的；婚生的' },
  { word: 'moderate', phonetic: '', meaning: '中等的；适度的；有节制的；温和的' },
  { word: 'oblivious', phonetic: '', meaning: '遗忘的；遗忘的；不注意的；不在意的' },
  { word: 'random', phonetic: '', meaning: '随便的；无目的的' },
  { word: 'relevant', phonetic: '', meaning: '有关的；切题的；有实际价值或重要性的' },
  { word: 'substantially', phonetic: '', meaning: '相当大的；基本上；本质的' },
  { word: 'temporary', phonetic: '', meaning: '暂时的临时的' },
  { word: 'unprecedented', phonetic: '', meaning: '史无前例的；空前的' },
  { word: 'versatile', phonetic: '', meaning: '多才多艺的；有多种用途的' },
  { word: 'accurate', phonetic: '', meaning: '准确的；正确无误的；精确的' },
  { word: 'alert', phonetic: '', meaning: '警觉的；留心的；机警的；敏捷的' },
  { word: 'approximately', phonetic: '', meaning: '大约；大概' },
  { word: 'distinctive', phonetic: '', meaning: '与众不同的；有特色的；显著的' },
  { word: 'dynamic', phonetic: '', meaning: '充满活力的；动力的' },
  { word: 'excessive', phonetic: '', meaning: '过多的；过度的；过分的' },
  { word: 'extraordinary', phonetic: '', meaning: '特别的；格外的；值得注意的' },
  { word: 'fragile', phonetic: '', meaning: '易碎的；易损坏的；脆弱的' },
  { word: 'inferior', phonetic: '', meaning: '品质差的；下等的；下级的' },
  { word: 'initial', phonetic: '', meaning: '开始的；最初的' },
  { word: 'irresistible', phonetic: '', meaning: '极为诱人的；无法抗拒的' },
  { word: 'miscellaneous', phonetic: '', meaning: '不同种类的；各式各样的；混杂的' },
  { word: 'Noteworthy', phonetic: '', meaning: '值得注意的；显著的' },
  { word: 'Rapid', phonetic: '', meaning: '迅速的；快速的；快的' },
  { word: 'self-explanatory', phonetic: '', meaning: '不需要加以说明的；不言自明的' },
  { word: 'Sufficient', phonetic: '', meaning: '足够的' },
  { word: 'Ultimately', phonetic: '', meaning: '最后；最终' },
  { word: 'Vague', phonetic: '', meaning: '含糊不清的；模糊不清的' },
  { word: 'Vivid', phonetic: '', meaning: '生龙活虎的；鲜艳的；鲜明的；生动逼真的' }
];
