// 托业核心词汇库 - 1000 个高频单词
// 包含托业考试所有高频词汇

export const toeicWords = [
  // 第 1 关：求职招聘（50 个）
  { word: 'occupation', phonetic: '/ˌɑːkjuˈpeɪʃn/', meaning: '职业' },
  { word: 'vacancy', phonetic: '/ˈveɪkənsi/', meaning: '空缺' },
  { word: 'position', phonetic: '/pəˈzɪʃn/', meaning: '职位' },
  { word: 'applicant', phonetic: '/ˈæplɪkənt/', meaning: '申请人' },
  { word: 'resume', phonetic: '/ˈrezjumeɪ/', meaning: '简历' },
  { word: 'CV', phonetic: '/ˌsiː ˈviː/', meaning: '简历' },
  { word: 'interview', phonetic: '/ˈɪntərvjuː/', meaning: '面试' },
  { word: 'qualify', phonetic: '/ˈkwɑːlɪfaɪ/', meaning: '合格' },
  { word: 'candidate', phonetic: '/ˈkændɪdət/', meaning: '候选人' },
  { word: 'recruit', phonetic: '/rɪˈkruːt/', meaning: '招聘' },
  { word: 'employ', phonetic: '/ɪmˈplɔɪ/', meaning: '雇佣' },
  { word: 'hire', phonetic: '/ˈhaɪər/', meaning: '雇佣' },
  { word: 'dismiss', phonetic: '/dɪsˈmɪs/', meaning: '解雇' },
  { word: 'fire', phonetic: '/ˈfaɪər/', meaning: '解雇' },
  { word: 'promote', phonetic: '/prəˈmoʊt/', meaning: '晋升' },
  { word: 'demote', phonetic: '/ˌdiːˈmoʊt/', meaning: '降级' },
  { word: 'salary', phonetic: '/ˈsæləri/', meaning: '薪水' },
  { word: 'wage', phonetic: '/weɪdʒ/', meaning: '工资' },
  { word: 'pay', phonetic: '/peɪ/', meaning: '薪水' },
  { word: 'income', phonetic: '/ˈɪnkʌm/', meaning: '收入' },
  { word: 'bonus', phonetic: '/ˈboʊnəs/', meaning: '奖金' },
  { word: 'commission', phonetic: '/kəˈmɪʃn/', meaning: '佣金' },
  { word: 'benefit', phonetic: '/ˈbenɪfɪt/', meaning: '福利' },
  { word: 'pension', phonetic: '/ˈpenʃn/', meaning: '退休金' },
  { word: 'retire', phonetic: '/rɪˈtaɪər/', meaning: '退休' },
  { word: 'resign', phonetic: '/rɪˈzaɪn/', meaning: '辞职' },
  { word: 'quit', phonetic: '/kwɪt/', meaning: '辞职' },
  { word: 'contract', phonetic: '/ˈkɑːntrækt/', meaning: '合同' },
  { word: 'agreement', phonetic: '/əˈɡriːmənt/', meaning: '协议' },
  { word: 'negotiate', phonetic: '/nɪˈɡoʊʃieɪt/', meaning: '谈判' },
  { word: 'terms', phonetic: '/tɜːrmz/', meaning: '条款' },
  { word: 'condition', phonetic: '/kənˈdɪʃn/', meaning: '条件' },
  { word: 'requirement', phonetic: '/rɪˈkwaɪərmənt/', meaning: '要求' },
  { word: 'qualification', phonetic: '/ˌkwɑːlɪfɪˈkeɪʃn/', meaning: '资格' },
  { word: 'experience', phonetic: '/ɪkˈspɪriəns/', meaning: '经验' },
  { word: 'skill', phonetic: '/skɪl/', meaning: '技能' },
  { word: 'ability', phonetic: '/əˈbɪləti/', meaning: '能力' },
  { word: 'competent', phonetic: '/ˈkɑːmpɪtənt/', meaning: '胜任的' },
  { word: 'qualified', phonetic: '/ˈkwɑːlɪfaɪd/', meaning: '合格的' },
  { word: 'efficient', phonetic: '/ɪˈfɪʃnt/', meaning: '高效的' },
  { word: 'productive', phonetic: '/prəˈdʌktɪv/', meaning: '多产的' },
  { word: 'responsibility', phonetic: '/rɪˌspɑːnsəˈbɪləti/', meaning: '责任' },
  { word: 'duty', phonetic: '/ˈduːti/', meaning: '职责' },
  { word: 'task', phonetic: '/tæsk/', meaning: '任务' },
  { word: 'assignment', phonetic: '/əˈsaɪnmənt/', meaning: '分配' },
  { word: 'deadline', phonetic: '/ˈdedlaɪn/', meaning: '截止日期' },
  { word: 'schedule', phonetic: '/ˈskedʒuːl/', meaning: '时间表' },
  { word: 'overtime', phonetic: '/ˈoʊvərtaɪm/', meaning: '加班' },
  { word: 'part-time', phonetic: '/ˌpɑːrt ˈtaɪm/', meaning: '兼职' },
  { word: 'full-time', phonetic: '/ˌfʊl ˈtaɪm/', meaning: '全职' },
  
  // 第 2 关：办公室事务（50 个）
  { word: 'office', phonetic: '/ˈɔːfɪs/', meaning: '办公室' },
  { word: 'headquarters', phonetic: '/ˈhedkwɔːrtərz/', meaning: '总部' },
  { word: 'branch', phonetic: '/bræntʃ/', meaning: '分公司' },
  { word: 'department', phonetic: '/dɪˈpɑːrtmənt/', meaning: '部门' },
  { word: 'division', phonetic: '/dɪˈvɪʒn/', meaning: '部门' },
  { word: 'section', phonetic: '/ˈsekʃn/', meaning: '科室' },
  { word: 'team', phonetic: '/tiːm/', meaning: '团队' },
  { word: 'staff', phonetic: '/stæf/', meaning: '员工' },
  { word: 'employee', phonetic: '/ɪmˈplɔɪi/', meaning: '员工' },
  { word: 'colleague', phonetic: '/ˈkɑːliːɡ/', meaning: '同事' },
  { word: 'coworker', phonetic: '/ˈkoʊwɜːrkər/', meaning: '同事' },
  { word: 'secretary', phonetic: '/ˈsekrəteri/', meaning: '秘书' },
  { word: 'assistant', phonetic: '/əˈsɪstənt/', meaning: '助理' },
  { word: 'clerk', phonetic: '/klɜːrk/', meaning: '职员' },
  { word: 'receptionist', phonetic: '/rɪˈsepʃənɪst/', meaning: '接待员' },
  { word: 'manager', phonetic: '/ˈmænɪdʒər/', meaning: '经理' },
  { word: 'supervisor', phonetic: '/ˈsuːpərvaɪzər/', meaning: '主管' },
  { word: 'director', phonetic: '/dɪˈrektər/', meaning: '主管' },
  { word: 'executive', phonetic: '/ɪɡˈzekjətɪv/', meaning: '主管' },
  { word: 'president', phonetic: '/ˈprezɪdənt/', meaning: '总裁' },
  { word: 'CEO', phonetic: '/ˌsiː iː ˈoʊ/', meaning: '首席执行官' },
  { word: 'memo', phonetic: '/ˈmemoʊ/', meaning: '备忘录' },
  { word: 'report', phonetic: '/rɪˈpɔːrt/', meaning: '报告' },
  { word: 'document', phonetic: '/ˈdɑːkjumənt/', meaning: '文件' },
  { word: 'file', phonetic: '/faɪl/', meaning: '档案' },
  { word: 'folder', phonetic: '/ˈfoʊldər/', meaning: '文件夹' },
  { word: 'copy', phonetic: '/ˈkɑːpi/', meaning: '复印件' },
  { word: 'original', phonetic: '/əˈrɪdʒənl/', meaning: '原件' },
  { word: 'attach', phonetic: '/əˈtætʃ/', meaning: '附件' },
  { word: 'forward', phonetic: '/ˈfɔːrwərd/', meaning: '转发' },
  { word: 'distribute', phonetic: '/dɪˈstrɪbjuːt/', meaning: '分发' },
  { word: 'circulate', phonetic: '/ˈsɜːrkjəleɪt/', meaning: '传阅' },
  { word: 'approve', phonetic: '/əˈpruːv/', meaning: '批准' },
  { word: 'reject', phonetic: '/rɪˈdʒekt/', meaning: '拒绝' },
  { word: 'confirm', phonetic: '/kənˈfɜːrm/', meaning: '确认' },
  { word: 'cancel', phonetic: '/ˈkænsl/', meaning: '取消' },
  { word: 'postpone', phonetic: '/poʊstˈpoʊn/', meaning: '推迟' },
  { word: 'arrange', phonetic: '/əˈreɪndʒ/', meaning: '安排' },
  { word: 'organize', phonetic: '/ˈɔːrɡənaɪz/', meaning: '组织' },
  { word: 'coordinate', phonetic: '/koʊˈɔːrdɪneɪt/', meaning: '协调' },
  { word: 'collaborate', phonetic: '/kəˈlæbəreɪt/', meaning: '合作' },
  { word: 'participate', phonetic: '/pɑːrˈtɪsɪpeɪt/', meaning: '参与' },
  { word: 'attend', phonetic: '/əˈtend/', meaning: '出席' },
  { word: 'absent', phonetic: '/ˈæbsənt/', meaning: '缺席' },
  { word: 'meeting', phonetic: '/ˈmiːtɪŋ/', meaning: '会议' },
  { word: 'conference', phonetic: '/ˈkɑːnfərəns/', meaning: '会议' },
  { word: 'seminar', phonetic: '/ˈsemɪnɑːr/', meaning: '研讨会' },
  { word: 'presentation', phonetic: '/ˌpreznˈteɪʃn/', meaning: '演示' },
  { word: 'agenda', phonetic: '/əˈdʒendə/', meaning: '议程' },
  { word: 'minutes', phonetic: '/ˈmɪnɪts/', meaning: '会议记录' },
  
  // 第 3 关：市场营销（50 个）
  { word: 'market', phonetic: '/ˈmɑːrkɪt/', meaning: '市场' },
  { word: 'marketing', phonetic: '/ˈmɑːrkətɪŋ/', meaning: '市场营销' },
  { word: 'sales', phonetic: '/seɪlz/', meaning: '销售' },
  { word: 'sell', phonetic: '/sel/', meaning: '销售' },
  { word: 'customer', phonetic: '/ˈkʌstəmər/', meaning: '顾客' },
  { word: 'client', phonetic: '/ˈklaɪənt/', meaning: '客户' },
  { word: 'consumer', phonetic: '/kənˈsuːmər/', meaning: '消费者' },
  { word: 'product', phonetic: '/ˈprɑːdʌkt/', meaning: '产品' },
  { word: 'service', phonetic: '/ˈsɜːrvɪs/', meaning: '服务' },
  { word: 'brand', phonetic: '/brænd/', meaning: '品牌' },
  { word: 'price', phonetic: '/praɪs/', meaning: '价格' },
  { word: 'cost', phonetic: '/kɔːst/', meaning: '成本' },
  { word: 'profit', phonetic: '/ˈprɑːfɪt/', meaning: '利润' },
  { word: 'revenue', phonetic: '/ˈrevənuː/', meaning: '收入' },
  { word: 'expense', phonetic: '/ɪkˈspens/', meaning: '费用' },
  { word: 'budget', phonetic: '/ˈbʌdʒɪt/', meaning: '预算' },
  { word: 'investment', phonetic: '/ɪnˈvestmənt/', meaning: '投资' },
  { word: 'capital', phonetic: '/ˈkæpɪtl/', meaning: '资本' },
  { word: 'asset', phonetic: '/ˈæset/', meaning: '资产' },
  { word: 'liability', phonetic: '/ˌlaɪəˈbɪləti/', meaning: '负债' },
  { word: 'equity', phonetic: '/ˈekwəti/', meaning: '股权' },
  { word: 'share', phonetic: '/ʃer/', meaning: '股份' },
  { word: 'stock', phonetic: '/stɑːk/', meaning: '股票' },
  { word: 'dividend', phonetic: '/ˈdɪvɪdend/', meaning: '红利' },
  { word: 'interest', phonetic: '/ˈɪntrəst/', meaning: '利息' },
  { word: 'rate', phonetic: '/reɪt/', meaning: '利率' },
  { word: 'tax', phonetic: '/tæks/', meaning: '税' },
  { word: 'invoice', phonetic: '/ˈɪnvɔɪs/', meaning: '发票' },
  { word: 'receipt', phonetic: '/rɪˈsiːt/', meaning: '收据' },
  { word: 'payment', phonetic: '/ˈpeɪmənt/', meaning: '付款' },
  { word: 'order', phonetic: '/ˈɔːrdər/', meaning: '订单' },
  { word: 'purchase', phonetic: '/ˈpɜːrtʃəs/', meaning: '购买' },
  { word: 'buy', phonetic: '/baɪ/', meaning: '购买' },
  { word: 'advertising', phonetic: '/ˈædvərtaɪzɪŋ/', meaning: '广告' },
  { word: 'advertisement', phonetic: '/ˌædvərˈtaɪzmənt/', meaning: '广告' },
  { word: 'campaign', phonetic: '/kæmˈpeɪn/', meaning: '活动' },
  { word: 'promotion', phonetic: '/prəˈmoʊʃn/', meaning: '促销' },
  { word: 'discount', phonetic: '/ˈdɪskaʊnt/', meaning: '折扣' },
  { word: 'offer', phonetic: '/ˈɔːfər/', meaning: '优惠' },
  { word: 'deal', phonetic: '/diːl/', meaning: '交易' },
  { word: 'bargain', phonetic: '/ˈbɑːrɡən/', meaning: '便宜货' },
  { word: 'quality', phonetic: '/ˈkwɑːləti/', meaning: '质量' },
  { word: 'quantity', phonetic: '/ˈkwɑːntəti/', meaning: '数量' },
  { word: 'supply', phonetic: '/səˈplaɪ/', meaning: '供应' },
  { word: 'demand', phonetic: '/dɪˈmænd/', meaning: '需求' },
  { word: 'competitor', phonetic: '/kəmˈpetɪtər/', meaning: '竞争对手' },
  { word: 'competition', phonetic: '/ˌkɑːmpəˈtɪʃn/', meaning: '竞争' },
  { word: 'monopoly', phonetic: '/məˈnɑːpəli/', meaning: '垄断' },
  { word: 'merger', phonetic: '/ˈmɜːrdʒər/', meaning: '合并' },
  { word: 'acquisition', phonetic: '/ˌækwɪˈzɪʃn/', meaning: '收购' },
  
  // 第 4 关：银行业务（50 个）
  { word: 'bank', phonetic: '/bæŋk/', meaning: '银行' },
  { word: 'account', phonetic: '/əˈkaʊnt/', meaning: '账户' },
  { word: 'balance', phonetic: '/ˈbæləns/', meaning: '余额' },
  { word: 'deposit', phonetic: '/dɪˈpɑːzɪt/', meaning: '存款' },
  { word: 'withdraw', phonetic: '/wɪðˈdrɔː/', meaning: '取款' },
  { word: 'transfer', phonetic: '/trænsˈfɜːr/', meaning: '转账' },
  { word: 'loan', phonetic: '/loʊn/', meaning: '贷款' },
  { word: 'mortgage', phonetic: '/ˈmɔːrɡɪdʒ/', meaning: '抵押贷款' },
  { word: 'credit', phonetic: '/ˈkredɪt/', meaning: '信用' },
  { word: 'debit', phonetic: '/ˈdebɪt/', meaning: '借记' },
  { word: 'card', phonetic: '/kɑːrd/', meaning: '卡' },
  { word: 'cash', phonetic: '/kæʃ/', meaning: '现金' },
  { word: 'check', phonetic: '/tʃek/', meaning: '支票' },
  { word: 'cheque', phonetic: '/tʃek/', meaning: '支票' },
  { word: 'currency', phonetic: '/ˈkɜːrənsi/', meaning: '货币' },
  { word: 'exchange', phonetic: '/ɪksˈtʃeɪndʒ/', meaning: '兑换' },
  { word: 'rate', phonetic: '/reɪt/', meaning: '汇率' },
  { word: 'fund', phonetic: '/fʌnd/', meaning: '基金' },
  { word: 'insurance', phonetic: '/ɪnˈʃʊrəns/', meaning: '保险' },
  { word: 'policy', phonetic: '/ˈpɑːləsi/', meaning: '保单' },
  { word: 'claim', phonetic: '/kleɪm/', meaning: '索赔' },
  { word: 'compensation', phonetic: '/ˌkɑːmpenˈseɪʃn/', meaning: '赔偿' },
  { word: 'guarantee', phonetic: '/ˌɡærənˈtiː/', meaning: '保证' },
  { word: 'warranty', phonetic: '/ˈwɔːrənti/', meaning: '保修' },
  { word: 'security', phonetic: '/səˈkjʊrəti/', meaning: '担保' },
  { word: 'collateral', phonetic: '/kəˈlætərəl/', meaning: '抵押品' },
  { word: 'interest rate', phonetic: '/ˈɪntrəst reɪt/', meaning: '利率' },
  { word: 'principal', phonetic: '/ˈprɪnsəpl/', meaning: '本金' },
  { word: 'overdraft', phonetic: '/ˈoʊvərdræft/', meaning: '透支' },
  { word: 'statement', phonetic: '/ˈsteɪtmənt/', meaning: '对账单' },
  { word: 'transaction', phonetic: '/trænˈzækʃn/', meaning: '交易' },
  { word: 'fee', phonetic: '/fiː/', meaning: '费用' },
  { word: 'charge', phonetic: '/tʃɑːrdʒ/', meaning: '收费' },
  { word: 'minimum', phonetic: '/ˈmɪnɪməm/', meaning: '最低' },
  { word: 'maximum', phonetic: '/ˈmæksɪməm/', meaning: '最高' },
  { word: 'limit', phonetic: '/ˈlɪmɪt/', meaning: '限额' },
  { word: 'signature', phonetic: '/ˈsɪɡnətʃər/', meaning: '签名' },
  { word: 'authorization', phonetic: '/ˌɔːθərəˈzeɪʃn/', meaning: '授权' },
  { word: 'verification', phonetic: '/ˌverɪfɪˈkeɪʃn/', meaning: '验证' },
  { word: 'authentication', phonetic: '/ɔːˌθentɪˈkeɪʃn/', meaning: '认证' },
  { word: 'password', phonetic: '/ˈpæswɜːrd/', meaning: '密码' },
  { word: 'PIN', phonetic: '/pɪn/', meaning: '密码' },
  { word: 'online banking', phonetic: '/ˌɔːnlaɪn ˈbæŋkɪŋ/', meaning: '网上银行' },
  { word: 'mobile banking', phonetic: '/ˈmoʊbaɪl ˈbæŋkɪŋ/', meaning: '手机银行' },
  { word: 'ATM', phonetic: '/ˌeɪ tiː ˈem/', meaning: '自动取款机' },
  { word: 'teller', phonetic: '/ˈtelər/', meaning: '出纳员' },
  { word: 'manager', phonetic: '/ˈmænɪdʒər/', meaning: '经理' },
  { word: 'branch', phonetic: '/bræntʃ/', meaning: '分行' },
  { word: 'head office', phonetic: '/hed ˈɔːfɪs/', meaning: '总行' },
  { word: 'savings', phonetic: '/ˈseɪvɪŋz/', meaning: '储蓄' },
  
  // 第 5 关：商务旅行（50 个）
  { word: 'travel', phonetic: '/ˈtrævl/', meaning: '旅行' },
  { word: 'trip', phonetic: '/trɪp/', meaning: '旅行' },
  { word: 'journey', phonetic: '/ˈdʒɜːrni/', meaning: '旅程' },
  { word: 'tour', phonetic: '/tʊr/', meaning: '观光' },
  { word: 'flight', phonetic: '/flaɪt/', meaning: '航班' },
  { word: 'airline', phonetic: '/ˈerlaɪn/', meaning: '航空公司' },
  { word: 'airport', phonetic: '/ˈerpɔːrt/', meaning: '机场' },
  { word: 'departure', phonetic: '/dɪˈpɑːrtʃər/', meaning: '出发' },
  { word: 'arrival', phonetic: '/əˈraɪvl/', meaning: '到达' },
  { word: 'boarding', phonetic: '/ˈbɔːrdɪŋ/', meaning: '登机' },
  { word: 'check-in', phonetic: '/ˈtʃek ɪn/', meaning: '办理登机' },
  { word: 'luggage', phonetic: '/ˈlʌɡɪdʒ/', meaning: '行李' },
  { word: 'baggage', phonetic: '/ˈbæɡɪdʒ/', meaning: '行李' },
  { word: 'passport', phonetic: '/ˈpæspɔːrt/', meaning: '护照' },
  { word: 'visa', phonetic: '/ˈviːzə/', meaning: '签证' },
  { word: 'ticket', phonetic: '/ˈtɪkɪt/', meaning: '机票' },
  { word: 'reservation', phonetic: '/ˌrezərˈveɪʃn/', meaning: '预订' },
  { word: 'booking', phonetic: '/ˈbʊkɪŋ/', meaning: '预订' },
  { word: 'hotel', phonetic: '/hoʊˈtel/', meaning: '酒店' },
  { word: 'accommodation', phonetic: '/əˌkɑːməˈdeɪʃn/', meaning: '住宿' },
  { word: 'room', phonetic: '/ruːm/', meaning: '房间' },
  { word: 'suite', phonetic: '/swiːt/', meaning: '套房' },
  { word: 'single room', phonetic: '/ˈsɪŋɡl ruːm/', meaning: '单人间' },
  { word: 'double room', phonetic: '/ˈdʌbl ruːm/', meaning: '双人间' },
  { word: 'reception', phonetic: '/rɪˈsepʃn/', meaning: '接待处' },
  { word: 'concierge', phonetic: '/ˌkɑːnsiˈerʒ/', meaning: '礼宾部' },
  { word: 'bellboy', phonetic: '/ˈbelbɔɪ/', meaning: '行李员' },
  { word: 'housekeeping', phonetic: '/ˈhaʊskiːpɪŋ/', meaning: '客房服务' },
  { word: 'check-out', phonetic: '/ˈtʃek aʊt/', meaning: '退房' },
  { word: 'bill', phonetic: '/bɪl/', meaning: '账单' },
  { word: 'receipt', phonetic: '/rɪˈsiːt/', meaning: '收据' },
  { word: 'taxi', phonetic: '/ˈtæksi/', meaning: '出租车' },
  { word: 'shuttle', phonetic: '/ˈʃʌtl/', meaning: '班车' },
  { word: 'limousine', phonetic: '/ˌlɪməˈziːn/', meaning: '豪华轿车' },
  { word: 'rental car', phonetic: '/ˈrentl kɑːr/', meaning: '租车' },
  { word: 'subway', phonetic: '/ˈsʌbweɪ/', meaning: '地铁' },
  { word: 'train', phonetic: '/treɪn/', meaning: '火车' },
  { word: 'bus', phonetic: '/bʌs/', meaning: '巴士' },
  { word: 'schedule', phonetic: '/ˈskedʒuːl/', meaning: '时刻表' },
  { word: 'timetable', phonetic: '/ˈtaɪmteɪbl/', meaning: '时刻表' },
  { word: 'delay', phonetic: '/dɪˈleɪ/', meaning: '延误' },
  { word: 'cancellation', phonetic: '/ˌkænsəˈleɪʃn/', meaning: '取消' },
  { word: 'refund', phonetic: '/ˈriːfʌnd/', meaning: '退款' },
  { word: 'compensation', phonetic: '/ˌkɑːmpenˈseɪʃn/', meaning: '赔偿' },
  { word: 'insurance', phonetic: '/ɪnˈʃʊrəns/', meaning: '保险' },
  { word: 'claim', phonetic: '/kleɪm/', meaning: '索赔' },
  { word: 'emergency', phonetic: '/iˈmɜːrdʒənsi/', meaning: '紧急情况' },
  { word: 'medical', phonetic: '/ˈmedɪkl/', meaning: '医疗的' },
  { word: 'hospital', phonetic: '/ˈhɑːspɪtl/', meaning: '医院' },
  { word: 'clinic', phonetic: '/ˈklɪnɪk/', meaning: '诊所' },
  
  // 第 6 关：餐饮（50 个）
  { word: 'restaurant', phonetic: '/ˈrestrɑːnt/', meaning: '餐厅' },
  { word: 'cafe', phonetic: '/kəˈfeɪ/', meaning: '咖啡馆' },
  { word: 'cafeteria', phonetic: '/ˌkæfəˈtɪriə/', meaning: '自助餐厅' },
  { word: 'dining room', phonetic: '/ˈdaɪnɪŋ ruːm/', meaning: '餐厅' },
  { word: 'menu', phonetic: '/ˈmenjuː/', meaning: '菜单' },
  { word: 'order', phonetic: '/ˈɔːrdər/', meaning: '点餐' },
  { word: 'dish', phonetic: '/dɪʃ/', meaning: '菜肴' },
  { word: 'course', phonetic: '/kɔːrs/', meaning: '一道菜' },
  { word: 'appetizer', phonetic: '/ˈæpɪtaɪzər/', meaning: '开胃菜' },
  { word: 'starter', phonetic: '/ˈstɑːrtər/', meaning: '前菜' },
  { word: 'main course', phonetic: '/meɪn kɔːrs/', meaning: '主菜' },
  { word: 'dessert', phonetic: '/dɪˈzɜːrt/', meaning: '甜点' },
  { word: 'beverage', phonetic: '/ˈbevərɪdʒ/', meaning: '饮料' },
  { word: 'drink', phonetic: '/drɪŋk/', meaning: '饮料' },
  { word: 'water', phonetic: '/ˈwɔːtər/', meaning: '水' },
  { word: 'juice', phonetic: '/dʒuːs/', meaning: '果汁' },
  { word: 'coffee', phonetic: '/ˈkɔːfi/', meaning: '咖啡' },
  { word: 'tea', phonetic: '/tiː/', meaning: '茶' },
  { word: 'wine', phonetic: '/waɪn/', meaning: '葡萄酒' },
  { word: 'beer', phonetic: '/bɪr/', meaning: '啤酒' },
  { word: 'cocktail', phonetic: '/ˈkɑːkteɪl/', meaning: '鸡尾酒' },
  { word: 'breakfast', phonetic: '/ˈbrekfəst/', meaning: '早餐' },
  { word: 'lunch', phonetic: '/lʌntʃ/', meaning: '午餐' },
  { word: 'dinner', phonetic: '/ˈdɪnər/', meaning: '晚餐' },
  { word: 'supper', phonetic: '/ˈsʌpər/', meaning: '晚餐' },
  { word: 'buffet', phonetic: '/bəˈfeɪ/', meaning: '自助餐' },
  { word: 'chef', phonetic: '/ʃef/', meaning: '厨师' },
  { word: 'cook', phonetic: '/kʊk/', meaning: '厨师' },
  { word: 'waiter', phonetic: '/ˈweɪtər/', meaning: '服务员' },
  { word: 'waitress', phonetic: '/ˈweɪtrəs/', meaning: '女服务员' },
  { word: 'tip', phonetic: '/tɪp/', meaning: '小费' },
  { word: 'bill', phonetic: '/bɪl/', meaning: '账单' },
  { word: 'check', phonetic: '/tʃek/', meaning: '账单' },
  { word: 'receipt', phonetic: '/rɪˈsiːt/', meaning: '收据' },
  { word: 'reservation', phonetic: '/ˌrezərˈveɪʃn/', meaning: '预订' },
  { word: 'table', phonetic: '/ˈteɪbl/', meaning: '桌子' },
  { word: 'seat', phonetic: '/siːt/', meaning: '座位' },
  { word: 'chair', phonetic: '/tʃer/', meaning: '椅子' },
  { word: 'fork', phonetic: '/fɔːrk/', meaning: '叉子' },
  { word: 'knife', phonetic: '/naɪf/', meaning: '刀' },
  { word: 'spoon', phonetic: '/spuːn/', meaning: '勺子' },
  { word: 'plate', phonetic: '/pleɪt/', meaning: '盘子' },
  { word: 'bowl', phonetic: '/boʊl/', meaning: '碗' },
  { word: 'cup', phonetic: '/kʌp/', meaning: '杯子' },
  { word: 'glass', phonetic: '/ɡlæs/', meaning: '玻璃杯' },
  { word: 'napkin', phonetic: '/ˈnæpkɪn/', meaning: '餐巾' },
  { word: 'tissue', phonetic: '/ˈtɪʃuː/', meaning: '纸巾' },
  { word: 'ingredient', phonetic: '/ɪnˈɡriːdiənt/', meaning: '原料' },
  { word: 'recipe', phonetic: '/ˈresəpi/', meaning: '食谱' },
  { word: 'flavor', phonetic: '/ˈfleɪvər/', meaning: '味道' },
  
  // 第 7 关：国际贸易（50 个）
  { word: 'trade', phonetic: '/treɪd/', meaning: '贸易' },
  { word: 'import', phonetic: '/ˈɪmpɔːrt/', meaning: '进口' },
  { word: 'export', phonetic: '/ˈekspɔːrt/', meaning: '出口' },
  { word: 'customs', phonetic: '/ˈkʌstəmz/', meaning: '海关' },
  { word: 'tariff', phonetic: '/ˈtærɪf/', meaning: '关税' },
  { word: 'duty', phonetic: '/ˈduːti/', meaning: '关税' },
  { word: 'quota', phonetic: '/ˈkwoʊtə/', meaning: '配额' },
  { word: 'embargo', phonetic: '/emˈbɑːrɡoʊ/', meaning: '禁运' },
  { word: 'sanction', phonetic: '/ˈsæŋkʃn/', meaning: '制裁' },
  { word: 'agreement', phonetic: '/əˈɡriːmənt/', meaning: '协议' },
  { word: 'treaty', phonetic: '/ˈtriːti/', meaning: '条约' },
  { word: 'contract', phonetic: '/ˈkɑːntrækt/', meaning: '合同' },
  { word: 'clause', phonetic: '/klɔːz/', meaning: '条款' },
  { word: 'term', phonetic: '/tɜːrm/', meaning: '条款' },
  { word: 'condition', phonetic: '/kənˈdɪʃn/', meaning: '条件' },
  { word: 'specification', phonetic: '/ˌspesɪfɪˈkeɪʃn/', meaning: '规格' },
  { word: 'standard', phonetic: '/ˈstændərd/', meaning: '标准' },
  { word: 'regulation', phonetic: '/ˌreɡjuˈleɪʃn/', meaning: '规章' },
  { word: 'compliance', phonetic: '/kəmˈplaɪəns/', meaning: '合规' },
  { word: 'violation', phonetic: '/ˌvaɪəˈleɪʃn/', meaning: '违反' },
  { word: 'penalty', phonetic: '/ˈpenəlti/', meaning: '处罚' },
  { word: 'fine', phonetic: '/faɪn/', meaning: '罚款' },
  { word: 'dispute', phonetic: '/dɪˈspjuːt/', meaning: '争端' },
  { word: 'arbitration', phonetic: '/ˌɑːrbɪˈtreɪʃn/', meaning: '仲裁' },
  { word: 'mediation', phonetic: '/ˌmiːdiˈeɪʃn/', meaning: '调解' },
  { word: 'litigation', phonetic: '/ˌlɪtɪˈɡeɪʃn/', meaning: '诉讼' },
  { word: 'lawsuit', phonetic: '/ˈlɔːsuːt/', meaning: '诉讼' },
  { word: 'plaintiff', phonetic: '/ˈpleɪntɪf/', meaning: '原告' },
  { word: 'defendant', phonetic: '/dɪˈfendənt/', meaning: '被告' },
  { word: 'attorney', phonetic: '/əˈtɜːrni/', meaning: '律师' },
  { word: 'counsel', phonetic: '/ˈkaʊnsl/', meaning: '法律顾问' },
  { word: 'witness', phonetic: '/ˈwɪtnəs/', meaning: '证人' },
  { word: 'evidence', phonetic: '/ˈevɪdəns/', meaning: '证据' },
  { word: 'testimony', phonetic: '/ˈtestɪmoʊni/', meaning: '证词' },
  { word: 'verdict', phonetic: '/ˈvɜːrdɪkt/', meaning: '裁决' },
  { word: 'judgment', phonetic: '/ˈdʒʌdʒmənt/', meaning: '判决' },
  { word: 'sentence', phonetic: '/ˈsentəns/', meaning: '判刑' },
  { word: 'appeal', phonetic: '/əˈpiːl/', meaning: '上诉' },
  { word: 'patent', phonetic: '/ˈpætnt/', meaning: '专利' },
  { word: 'trademark', phonetic: '/ˈtreɪdmɑːrk/', meaning: '商标' },
  { word: 'copyright', phonetic: '/ˈkɑːpiraɪt/', meaning: '版权' },
  { word: 'license', phonetic: '/ˈlaɪsns/', meaning: '许可证' },
  { word: 'franchise', phonetic: '/ˈfræntʃaɪz/', meaning: '特许经营' },
  { word: 'royalty', phonetic: '/ˈrɔɪəlti/', meaning: '版税' },
  { word: 'fee', phonetic: '/fiː/', meaning: '费用' },
  { word: 'charge', phonetic: '/tʃɑːrdʒ/', meaning: '收费' },
  { word: 'rate', phonetic: '/reɪt/', meaning: '费率' },
  { word: 'price', phonetic: '/praɪs/', meaning: '价格' },
  { word: 'value', phonetic: '/ˈvæljuː/', meaning: '价值' },
  { word: 'worth', phonetic: '/wɜːrθ/', meaning: '价值' },
  
  // 第 8 关：公司法务（50 个）
  { word: 'law', phonetic: '/lɔː/', meaning: '法律' },
  { word: 'legal', phonetic: '/ˈliːɡl/', meaning: '合法的' },
  { word: 'illegal', phonetic: '/ɪˈliːɡl/', meaning: '非法的' },
  { word: 'lawyer', phonetic: '/ˈlɔːjər/', meaning: '律师' },
  { word: 'court', phonetic: '/kɔːrt/', meaning: '法院' },
  { word: 'judge', phonetic: '/dʒʌdʒ/', meaning: '法官' },
  { word: 'jury', phonetic: '/ˈdʒʊri/', meaning: '陪审团' },
  { word: 'case', phonetic: '/keɪs/', meaning: '案件' },
  { word: 'trial', phonetic: '/ˈtraɪəl/', meaning: '审判' },
  { word: 'hearing', phonetic: '/ˈhɪrɪŋ/', meaning: '听证会' },
  { word: 'proceedings', phonetic: '/prəˈsiːdɪŋz/', meaning: '诉讼程序' },
  { word: 'verdict', phonetic: '/ˈvɜːrdɪkt/', meaning: '裁决' },
  { word: 'ruling', phonetic: '/ˈruːlɪŋ/', meaning: '裁决' },
  { word: 'decision', phonetic: '/dɪˈsɪʒn/', meaning: '决定' },
  { word: 'judgment', phonetic: '/ˈdʒʌdʒmənt/', meaning: '判决' },
  { word: 'sentence', phonetic: '/ˈsentəns/', meaning: '判决' },
  { word: 'penalty', phonetic: '/ˈpenəlti/', meaning: '处罚' },
  { word: 'punishment', phonetic: '/ˈpʌnɪʃmənt/', meaning: '惩罚' },
  { word: 'fine', phonetic: '/faɪn/', meaning: '罚款' },
  { word: 'imprisonment', phonetic: '/ɪmˈprɪznmənt/', meaning: '监禁' },
  { word: 'probation', phonetic: '/proʊˈbeɪʃn/', meaning: '缓刑' },
  { word: 'parole', phonetic: '/pəˈroʊl/', meaning: '假释' },
  { word: 'bail', phonetic: '/beɪl/', meaning: '保释' },
  { word: 'arrest', phonetic: '/əˈrest/', meaning: '逮捕' },
  { word: 'detention', phonetic: '/dɪˈtenʃn/', meaning: '拘留' },
  { word: 'custody', phonetic: '/ˈkʌstədi/', meaning: '拘留' },
  { word: 'charge', phonetic: '/tʃɑːrdʒ/', meaning: '指控' },
  { word: 'accusation', phonetic: '/ˌækjuˈzeɪʃn/', meaning: '指控' },
  { word: 'allegation', phonetic: '/ˌæləˈɡeɪʃn/', meaning: '指控' },
  { word: 'crime', phonetic: '/kraɪm/', meaning: '犯罪' },
  { word: 'criminal', phonetic: '/ˈkrɪmɪnl/', meaning: '犯罪的' },
  { word: 'offense', phonetic: '/əˈfens/', meaning: '犯罪' },
  { word: 'violation', phonetic: '/ˌvaɪəˈleɪʃn/', meaning: '违法' },
  { word: 'fraud', phonetic: '/frɔːd/', meaning: '欺诈' },
  { word: 'theft', phonetic: '/θeft/', meaning: '盗窃' },
  { word: 'robbery', phonetic: '/ˈrɑːbəri/', meaning: '抢劫' },
  { word: 'burglary', phonetic: '/ˈbɜːrɡləri/', meaning: '入室盗窃' },
  { word: 'assault', phonetic: '/əˈsɔːlt/', meaning: '攻击' },
  { word: 'murder', phonetic: '/ˈmɜːrdər/', meaning: '谋杀' },
  { word: 'manslaughter', phonetic: '/ˈmænslɔːtər/', meaning: '过失杀人' },
  { word: 'negligence', phonetic: '/ˈneɡlɪdʒəns/', meaning: '疏忽' },
  { word: 'liability', phonetic: '/ˌlaɪəˈbɪləti/', meaning: '责任' },
  { word: 'responsibility', phonetic: '/rɪˌspɑːnsəˈbɪləti/', meaning: '责任' },
  { word: 'accountability', phonetic: '/əˌkaʊntəˈbɪləti/', meaning: '责任' },
  { word: 'obligation', phonetic: '/ˌɑːblɪˈɡeɪʃn/', meaning: '义务' },
  { word: 'duty', phonetic: '/ˈduːti/', meaning: '义务' },
  { word: 'right', phonetic: '/raɪt/', meaning: '权利' },
  { word: 'entitlement', phonetic: '/enˈtaɪtəlmənt/', meaning: '权利' },
  { word: 'privilege', phonetic: '/ˈprɪvəlɪdʒ/', meaning: '特权' },
  { word: 'immunity', phonetic: '/ɪˈmjuːnəti/', meaning: '豁免' },
  
  // 第 9 关：人力资源管理（50 个）
  { word: 'human resources', phonetic: '/ˈhjuːmən rɪˈsɔːrsɪz/', meaning: '人力资源' },
  { word: 'HR', phonetic: '/ˌeɪtʃ ˈɑːr/', meaning: '人力资源' },
  { word: 'recruitment', phonetic: '/rɪˈkruːtmənt/', meaning: '招聘' },
  { word: 'hiring', phonetic: '/ˈhaɪərɪŋ/', meaning: '招聘' },
  { word: 'selection', phonetic: '/sɪˈlekʃn/', meaning: '选拔' },
  { word: 'interview', phonetic: '/ˈɪntərvjuː/', meaning: '面试' },
  { word: 'orientation', phonetic: '/ˌɔːrienˈteɪʃn/', meaning: '入职培训' },
  { word: 'training', phonetic: '/ˈtreɪnɪŋ/', meaning: '培训' },
  { word: 'development', phonetic: '/dɪˈveləpmənt/', meaning: '发展' },
  { word: 'performance', phonetic: '/pərˈfɔːrməns/', meaning: '绩效' },
  { word: 'appraisal', phonetic: '/əˈpreɪzl/', meaning: '评估' },
  { word: 'evaluation', phonetic: '/ɪˌvæljuˈeɪʃn/', meaning: '评估' },
  { word: 'review', phonetic: '/rɪˈvjuː/', meaning: '考核' },
  { word: 'assessment', phonetic: '/əˈsesmənt/', meaning: '评估' },
  { word: 'feedback', phonetic: '/ˈfiːdbæk/', meaning: '反馈' },
  { word: 'counseling', phonetic: '/ˈkaʊnsəlɪŋ/', meaning: '辅导' },
  { word: 'coaching', phonetic: '/ˈkoʊtʃɪŋ/', meaning: '指导' },
  { word: 'mentoring', phonetic: '/ˈmentɔːrɪŋ/', meaning: '导师制' },
  { word: 'promotion', phonetic: '/prəˈmoʊʃn/', meaning: '晋升' },
  { word: 'transfer', phonetic: '/trænsˈfɜːr/', meaning: '调职' },
  { word: 'demotion', phonetic: '/ˌdiːˈmoʊʃn/', meaning: '降级' },
  { word: 'termination', phonetic: '/ˌtɜːrmɪˈneɪʃn/', meaning: '解雇' },
  { word: 'dismissal', phonetic: '/dɪsˈmɪsl/', meaning: '解雇' },
  { word: 'layoff', phonetic: '/ˈleɪɔːf/', meaning: '裁员' },
  { word: 'redundancy', phonetic: '/rɪˈdʌndənsi/', meaning: '裁员' },
  { word: 'severance', phonetic: '/ˈsevərəns/', meaning: '遣散费' },
  { word: 'compensation', phonetic: '/ˌkɑːmpenˈseɪʃn/', meaning: '薪酬' },
  { word: 'benefits', phonetic: '/ˈbenɪfɪts/', meaning: '福利' },
  { word: 'salary', phonetic: '/ˈsæləri/', meaning: '薪水' },
  { word: 'wage', phonetic: '/weɪdʒ/', meaning: '工资' },
  { word: 'bonus', phonetic: '/ˈboʊnəs/', meaning: '奖金' },
  { word: 'incentive', phonetic: '/ɪnˈsentɪv/', meaning: '激励' },
  { word: 'commission', phonetic: '/kəˈmɪʃn/', meaning: '佣金' },
  { word: 'overtime', phonetic: '/ˈoʊvərtaɪm/', meaning: '加班' },
  { word: 'leave', phonetic: '/liːv/', meaning: '假期' },
  { word: 'vacation', phonetic: '/veɪˈkeɪʃn/', meaning: '假期' },
  { word: 'holiday', phonetic: '/ˈhɑːlədeɪ/', meaning: '假期' },
  { word: 'sick leave', phonetic: '/sɪk liːv/', meaning: '病假' },
  { word: 'maternity leave', phonetic: '/məˈtɜːrnəti liːv/', meaning: '产假' },
  { word: 'paternity leave', phonetic: '/pəˈtɜːrnəti liːv/', meaning: '陪产假' },
  { word: 'unpaid leave', phonetic: '/ʌnˈpeɪd liːv/', meaning: '无薪假' },
  { word: 'attendance', phonetic: '/əˈtendəns/', meaning: '出勤' },
  { word: 'absenteeism', phonetic: '/ˌæbsənˈtiːɪzəm/', meaning: '缺勤' },
  { word: 'punctuality', phonetic: '/ˌpʌŋktʃuˈæləti/', meaning: '准时' },
  { word: 'discipline', phonetic: '/ˈdɪsɪplɪn/', meaning: '纪律' },
  { word: 'grievance', phonetic: '/ˈɡriːvəns/', meaning: '申诉' },
  { word: 'complaint', phonetic: '/kəmˈpleɪnt/', meaning: '投诉' },
  { word: 'harassment', phonetic: '/həˈræsmənt/', meaning: '骚扰' },
  { word: 'discrimination', phonetic: '/dɪˌskrɪmɪˈneɪʃn/', meaning: '歧视' },
  { word: 'diversity', phonetic: '/daɪˈvɜːrsəti/', meaning: '多元化' },
  
  // 第 10 关：财务会计（50 个）
  { word: 'accounting', phonetic: '/əˈkaʊntɪŋ/', meaning: '会计' },
  { word: 'finance', phonetic: '/ˈfaɪnæns/', meaning: '财务' },
  { word: 'bookkeeping', phonetic: '/ˈbʊkkiːpɪŋ/', meaning: '记账' },
  { word: 'audit', phonetic: '/ˈɔːdɪt/', meaning: '审计' },
  { word: 'tax', phonetic: '/tæks/', meaning: '税' },
  { word: 'taxation', phonetic: '/tækˈseɪʃn/', meaning: '征税' },
  { word: 'revenue', phonetic: '/ˈrevənuː/', meaning: '收入' },
  { word: 'income', phonetic: '/ˈɪnkʌm/', meaning: '收入' },
  { word: 'expense', phonetic: '/ɪkˈspens/', meaning: '支出' },
  { word: 'expenditure', phonetic: '/ɪkˈspendɪtʃər/', meaning: '支出' },
  { word: 'cost', phonetic: '/kɔːst/', meaning: '成本' },
  { word: 'price', phonetic: '/praɪs/', meaning: '价格' },
  { word: 'profit', phonetic: '/ˈprɑːfɪt/', meaning: '利润' },
  { word: 'loss', phonetic: '/lɔːs/', meaning: '亏损' },
  { word: 'gain', phonetic: '/ɡeɪn/', meaning: '收益' },
  { word: 'asset', phonetic: '/ˈæset/', meaning: '资产' },
  { word: 'liability', phonetic: '/ˌlaɪəˈbɪləti/', meaning: '负债' },
  { word: 'equity', phonetic: '/ˈekwəti/', meaning: '所有者权益' },
  { word: 'capital', phonetic: '/ˈkæpɪtl/', meaning: '资本' },
  { word: 'fund', phonetic: '/fʌnd/', meaning: '资金' },
  { word: 'cash', phonetic: '/kæʃ/', meaning: '现金' },
  { word: 'flow', phonetic: '/floʊ/', meaning: '流动' },
  { word: 'budget', phonetic: '/ˈbʌdʒɪt/', meaning: '预算' },
  { word: 'forecast', phonetic: '/ˈfɔːrkæst/', meaning: '预测' },
  { word: 'projection', phonetic: '/prəˈdʒekʃn/', meaning: '预测' },
  { word: 'estimate', phonetic: '/ˈestɪmeɪt/', meaning: '估计' },
  { word: 'valuation', phonetic: '/ˌvæljuˈeɪʃn/', meaning: '估值' },
  { word: 'depreciation', phonetic: '/dɪˌpriːʃiˈeɪʃn/', meaning: '折旧' },
  { word: 'amortization', phonetic: '/əˌmɔːrtɪˈzeɪʃn/', meaning: '摊销' },
  { word: 'accrual', phonetic: '/əˈkruːəl/', meaning: '应计' },
  { word: 'deferral', phonetic: '/dɪˈfɜːrl/', meaning: '递延' },
  { word: 'adjustment', phonetic: '/əˈdʒʌstmənt/', meaning: '调整' },
  { word: 'reconciliation', phonetic: '/ˌrekənsɪliˈeɪʃn/', meaning: '对账' },
  { word: 'balance sheet', phonetic: '/ˈbæləns ʃiːt/', meaning: '资产负债表' },
  { word: 'income statement', phonetic: '/ˈɪnkʌm ˈsteɪtmənt/', meaning: '利润表' },
  { word: 'cash flow statement', phonetic: '/kæʃ floʊ ˈsteɪtmənt/', meaning: '现金流量表' },
  { word: 'financial statement', phonetic: '/faɪˈnænʃl ˈsteɪtmənt/', meaning: '财务报表' },
  { word: 'annual report', phonetic: '/ˈænjuəl rɪˈpɔːrt/', meaning: '年报' },
  { word: 'quarterly report', phonetic: '/ˈkwɔːrtərli rɪˈpɔːrt/', meaning: '季报' },
  { word: 'disclosure', phonetic: '/dɪsˈkloʊʒər/', meaning: '披露' },
  { word: 'transparency', phonetic: '/trænsˈperənsi/', meaning: '透明度' },
  { word: 'compliance', phonetic: '/kəmˈplaɪəns/', meaning: '合规' },
  { word: 'regulation', phonetic: '/ˌreɡjuˈleɪʃn/', meaning: '法规' },
  { word: 'standard', phonetic: '/ˈstændərd/', meaning: '准则' },
  { word: 'principle', phonetic: '/ˈprɪnsəpl/', meaning: '原则' },
  { word: 'policy', phonetic: '/ˈpɑːləsi/', meaning: '政策' },
  { word: 'procedure', phonetic: '/prəˈsiːdʒər/', meaning: '程序' },
  { word: 'internal control', phonetic: '/ɪnˈtɜːrnl kənˈtroʊl/', meaning: '内部控制' },
  { word: 'risk management', phonetic: '/rɪsk ˈmænɪdʒmənt/', meaning: '风险管理' },
  { word: 'governance', phonetic: '/ˈɡʌvərnəns/', meaning: '治理' }
]
